### ISSUE TITLE
Feature: JEI-like header with with different crafting methods

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/NotEnoughItems#10]
Are you planning to add something similar?
![image](https://user-images.githubusercontent.com/29896317/73131297-a7b15c00-4019-11ea-8b43-48a61bf44f76.png)

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by mitchej123** [comment]
At some point.  Also willing to take PRs.

**Comment by talchas** [comment]
https://github.com/talchas/NotEnoughItems/commit/fed501e6d2f4a717175c54ebd510b3d5730e781f is a super basic version of it; it doesn't handle anything like paginating them or handling larger ui sizes where the names get long (and run off the top of the screen) or anything like that. If anyone wants to clean it up into something more polished, or you want to take it as-is, feel free.

**Comment by mitchej123** [comment]
In beta.
