### ISSUE TITLE
OC API display is borked

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/NotEnoughItems#100]
![image](https://user-images.githubusercontent.com/16054364/114968173-b0fb3400-9e2a-11eb-972d-4283f0857d19.png)

**Comment by mitchej123** [comment]
Please give this build a try http://jenkins.usrv.eu:8080/job/NEI/61/artifact/build/libs/NotEnoughItems-1.7.10-2.1.2-GTNH-universal.jar

**Comment by MatthewCOwen** [comment]
![image](https://user-images.githubusercontent.com/16054364/115090160-f9692f00-9ec8-11eb-88b4-55a13b18c064.png)
👍
