### ISSUE TITLE
Game Crashes when trying to favorite certain items from OpenComputers

### ISSUE THREAD

**Issue by MadMan310** [GTNewHorizons/NotEnoughItems#101]
This happens when I favorite the EEPROM (Lua bios) and the tablet from OC.

[crash-2021-04-15_20.44.43-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6322333/crash-2021-04-15_20.44.43-client.txt)

**Comment by ORANG4** [comment]
Similar crash with machines from Thermal Expansion. e.g. Magma Crucible

**Comment by mitchej123** [comment]
Huh, would have thought NBTPrimative would have caught NBTByte... Will take a look.

**Comment by mitchej123** [comment]
Ah, NBTByteArray... 

Please give this build a try http://jenkins.usrv.eu:8080/job/NEI/61/artifact/build/libs/NotEnoughItems-1.7.10-2.1.2-GTNH-universal.jar

**Comment by mitchej123** [comment]
> Similar crash when trying to bookmark machines from Thermal Expansion. e.g. Magma Crucible

If it's `java.lang.IllegalArgumentException: Unsupported NBT Tag: BYTE[]` that should be fixed.  If it's another type, please post the log here after grabbing the 2.1.2 linked above.
