### ISSUE TITLE
The GT Ore vein information page overlaps with multiple entries and is rendered completely illegible

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/NotEnoughItems#106]
Here's a picture worth more than a thousand words.
![2021-04-17_20 13 34](https://user-images.githubusercontent.com/5557920/115139625-33564480-a033-11eb-8b4f-58ba054966a3.png)

A bit of an added information: I am using a dead GT6 NEI handler that is rather hard to find, let me know if you need the actual handler for this in case if it's possible to make a per-handler exclusion to reduce the amount of ores displayed to 1 per page in case.

Thanks in advance!

**Comment by mitchej123** [comment]
A few bits of information I'll need:
1) Hover over the tab and hold SHIFT; it'll give the relevant handler information
2) Go to NEI Settings --> tools --> data dumps --> Handler Dump [CSV].  It'll dump a csv of all registered handlers, yours should be listed as UNKNOWN.  Copy and paste the handler class
3) Update the issue


Alternative 3) Go to NEI Settings --> Tools --> Load Config from --> {Jar} and change it to CSV;  Edit the `config/NEI/handlers.csv`, add your handler (following the patter), adjust the `handlerHeight`.  Then SHIFT click the NEI settings wrench, which will trigger a handler reload.  Assuming there's no error logs, close and reopen the handler and it should be updated.

**Comment by tyrael93** [comment]
Awesome, thank you! Got it to work with the config route, and now that I know how it works I can tweak the handlers myself.
![trabajo](https://user-images.githubusercontent.com/5557920/115160921-fcb41480-a09a-11eb-865d-6c9d66d2eaba.png)

**Comment by mitchej123** [comment]
For any other mods please consider sending a PR or handler info in an issue so we can ship it by default
