### ISSUE TITLE
Visual bug with Bart Works devices 2.0.1.6

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NotEnoughItems#107]
Bart devices like Bio Vat an Bio Lab shows a tiner grey border.

https://cdn.discordapp.com/attachments/386772579274326016/833313629017210901/unknown.png

https://cdn.discordapp.com/attachments/386772579274326016/833313830700318750/unknown.png

Last build from Jenkins

**Comment by Prometheus0000** [comment]
Updated sheet to fix
