### ISSUE TITLE
Clicking on a bookmarked item does not show recipe

### ISSUE THREAD

**Issue by Nagapito** [GTNewHorizons/NotEnoughItems#11]
I do need to press R while hovering the bookmarked item for it to show the recipe.
Left/right click interaction to show recipe and used in recipes like on the right side of NEI would be awesome.

Specially since most of the times, instead of pressing R, for some reason I actually press A, since in my brain A is the normal key to press on that side of the NEI screen and I end up removing the bookmark...

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by Dream-Master** [comment]
@Nagapito what version of Nei do you use ?

**Comment by mitchej123** [comment]
The current thought is the potion effects are Z fighting with the bookmarks and winning (for clicking).  I have not had a chance to track this down.  For how use R/U.

**Comment by Nagapito** [comment]
currently using the beta-1 that comes with the pack but, I will update to the beta-3 since I am going to have dinner and need to close the client.

**Comment by Nagapito** [comment]
confirmed also on beta-3

**Comment by Nagapito** [comment]
Something I just noticed, if I open the inventory (mine or a machine/chest), clicking on the bookmarks does not work as I reported but...
If I am seeing a recipe, the clicks do work. 
If I go from the recipe back to the inventory, the clicks stop working again

**Comment by MineAnPlay** [comment]
Also I would like to add that you can't spawn items from bookmarks in cheat mode either.

**Comment by mitchej123** [comment]
I think it's the potion effect GUI that's blocking it, and that's not visible with the recipe.  Or that's the current hunch.

Supporting the cheat mode on bookmarks is low on the list, haven't even looked at it.

**Comment by MineAnPlay** [comment]
Potion Effect trying to "overwrite" it could be the issue BUT it can't be it because potion effects aren't visible in inventories other then the players inventory. I wouldn't want to overrule it because it might just be how vanilla handles GUIs but my hunch is that it isn't because of it. You said the icons are identical to the right (which I think is true as when you are viewing recipes (using NEIs GUI) it works with no issue at all but outside of it it doesn't work. Maybe NEI doesn't just add handling to the icons but also the tab the icons reside on?

**Comment by mitchej123** [comment]
Something is intercepting the click event, but I haven't tracked down what it is.  If someone finds it for me, it'll be much easier to fix :)

**Comment by mitchej123** [comment]
Might have a fix that Montann provided; will try it out tonight.

**Comment by mitchej123** [comment]
Fixed in https://github.com/GTNewHorizons/NotEnoughItems/commit/bb40acc7a342181cfc3957895bc8cc5ffa55ba29 available in the latest release - 
 https://github.com/GTNewHorizons/NotEnoughItems/releases/download/2.0.0-beta-4/NotEnoughItems-1.7.10-2.0.0-beta-4-GTNH-universal.jar
