### ISSUE TITLE
crash using GTNEI with po2 kappa

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NotEnoughItems#111]
crashlog paste:  https://pastebin.com/xX4ceBMY

NotEnoughItems-1.7.10-2.1.1-GTNH-universal

reproducible.  tried two times.  I tried to A over the thermal expansions auto activator and ctd with above crashlog.

third time going in and going into nei to wait for rules / hiding / whatever they use in the pack to basically hide the facades, etc... I crashed out w/o any interaction in almost the same crashlog. I probably jumped into nei too early after starting map.

I know this isn't gtnh, so not assuming it'll get fixed unless you find some generic wierdness with it.  

Thanks man

**Comment by mitchej123** [comment]
This should be fixed in 2.1.2 -- grab it from https://github.com/GTNewHorizons/NotEnoughItems/releases/tag/2.1.2-GTNH

**Comment by mitchej123** [comment]
lmk if 2.1.2 doesn't fix it an I'll reopen

**Comment by DoomSquirter** [comment]
looks like it solved the crash, thanks alot
