### ISSUE TITLE
Crashing Whenever I try to play

### ISSUE THREAD

**Issue by Tacoon2x4** [GTNewHorizons/NotEnoughItems#112]
Every time i go to open Minecraft with this mod it crashes and says error code; 0

**Comment by Prometheus0000** [comment]
1) This is a modpack not a mod
2) Post the crashlog or any kind of useful log if you can't find that one

**Comment by Prometheus0000** [comment]
Please post the crashlog.

**Comment by Tacoon2x4** [comment]
> Every time i go to open Minecraft with this mod it crashes and says error code; 0
