### ISSUE TITLE
Automagy crash

### ISSUE THREAD

**Issue by Fabboz** [GTNewHorizons/NotEnoughItems#115]
crash when looking recipe of arcane stone made of silver shard.
[crash-2021-05-03_10.59.07-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6413870/crash-2021-05-03_10.59.07-client.txt)

**Comment by Glease** [comment]
Sounds like a problem with automagy itself. Try if other versions of NEI would crash.

**Comment by Fabboz** [comment]
regular old nei 1.0.5.120-universal don't crash. but the oredict recipe don't work it only show the one with silver of air that is metadata 0.

**Comment by mitchej123** [comment]
I believe a guard was put in against this; if it happens again reopen.
