### ISSUE TITLE
Found a crash when using the machine-buttons at the top

### ISSUE THREAD

**Issue by Zanciks** [GTNewHorizons/NotEnoughItems#117]
I looked at the uses for a Gold Coin from Thaumcraft, scrolled to page 3, clicked on the furnace (which was on page 3/1 and didn't show anything) and then upon clicking on "Shapeless Recipes" the game crashed.

[crash-2021-05-05_18.41.50-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6431016/crash-2021-05-05_18.41.50-client.txt)

**Comment by mitchej123** [comment]
You're on an old beta `NotEnoughItems-1.7.10-2.1.0-GTNH-beta-universal.jar`  Please update to https://github.com/GTNewHorizons/NotEnoughItems/releases/tag/2.1.2-GTNH
