### ISSUE TITLE
You don't have instructions on how to actually use this mod

### ISSUE THREAD

**Issue by Mattnelxd** [GTNewHorizons/NotEnoughItems#119]
I made a github account just for this purpose because I don't like nei

**Comment by Mattnelxd** [comment]
Actually meant to say you don't give instructions on how to download it, every time I move the file to my mod folder my game will crash

**Comment by mitchej123** [comment]
Need a crashlog

**Comment by mitchej123** [comment]
Did you remove the old version before adding the new one?

**Comment by Mattnelxd** [comment]
Yes but the old one gets added while starting the game

**Comment by mitchej123** [comment]
look for `config/dependencies.json` or something similar and remove it
