### ISSUE TITLE
Bookmarking Thermal Expansion machines crashes the game

### ISSUE THREAD

**Issue by Milesman34** [GTNewHorizons/NotEnoughItems#124]
Bookmarking a Thermal Expansion machine appears to crash the game. I attempted to pin the Induction Smelter, but it crashed all 3 times I tried. I was able to view the recipe. This happened earlier on with the Autonomous Activator too.

Pack: Project Ozone 2 Reloaded (Kappa Mode)
Version of NEI: GTNH beta 13

**Comment by mitchej123** [comment]
Please update, this has been fixed https://github.com/GTNewHorizons/NotEnoughItems/releases/tag/2.1.2-GTNH
