### ISSUE TITLE
Incorrect Position of Thaumcraft Aspects on NEI Aspect Combination page

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/NotEnoughItems#125]
In Gregtech: New Horizons, version 2.1.0.6 with NEI updated to the latest version off of the jenkins, based on commit ae1d0d9

The Aspects shown on the Aspect combining NEI page are not scaled to the length of the entire NEI page, and in addition can render incorrectly, some times even off of the NEI page.

The following images are from looking at the usages of `Terra` Aspect from NEI:
Page 1:
![javaw_2021-05-14_20-16-45](https://user-images.githubusercontent.com/31759736/118346679-1443b900-b4f2-11eb-9d5e-be7503d15615.png)

Page 2:
![javaw_2021-05-14_20-16-56](https://user-images.githubusercontent.com/31759736/118346684-1ad23080-b4f2-11eb-8c68-67d4d1e64613.png)

Page 3:
![javaw_2021-05-14_20-17-05](https://user-images.githubusercontent.com/31759736/118346692-2160a800-b4f2-11eb-8e57-f9f859b95a66.png)

Page 4:
![javaw_2021-05-14_20-17-20](https://user-images.githubusercontent.com/31759736/118346694-26255c00-b4f2-11eb-8c2a-54ff224cba3e.png)

I would expect the aspects to scale all the way down the NEI page, if possible, instead of being divided into multiple pages. In addition, for the aspect combinations to render on the page, instead of off of the page or colliding with other GUI elements.

**Comment by Prometheus0000** [comment]
Looks like there's a hard limit of 5 per page. 60 and 5 works ok, unless the code is edited.
![image](https://user-images.githubusercontent.com/8517039/118364353-24957b80-b566-11eb-8fe6-5c5f814957f1.png)
![image](https://user-images.githubusercontent.com/8517039/118364360-295a2f80-b566-11eb-895d-3d4e3cae8678.png)

**Comment by Prometheus0000** [comment]
```java
    @Override
    public int recipiesPerPage() {
        return 5;
    }
```

In the https://github.com/GTNewHorizons/TCNEIAdditions/blob/master/src/main/java/ru/timeconqueror/tcneiadditions/nei/AspectCombinationHandler.java file. Any reason not to change it?

**Comment by mitchej123** [comment]
I believe this has been addressed.
