### ISSUE TITLE
Client Crash when shift-clicking a processing (not crafting) recipe in the "Just enough Calculations" Crafting Calculator

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/NotEnoughItems#129]
See Title, Client Crash Report :
[crash-2021-05-15_16.49.13-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6489307/crash-2021-05-15_16.49.13-client.txt)

Playing on local server, only client crashes

**Comment by mitchej123** [comment]
Where did you download this from? It doesn't follow the filename pattern I see on curse, and doesn't seem to match the github I found for it.

**Comment by TrainerSnow** [comment]
I got it from Curseforge, though i will close this, because someone just released a forked version of it which is compatible with the GT:NH NEI: https://github.com/Discreater/JustEnoughCalculation/releases . Thanks for looking into it tho.
