### ISSUE TITLE
[Feature] Crafttweaker with nei

### ISSUE THREAD

**Issue by Sa1ZeR** [GTNewHorizons/NotEnoughItems#137]
I am using the CraftTweaker with NEI, I have a script that removes items from the list of NEI. Some code:
 import mods.nei.NEI;

NEI.hide(<minecraft:mob_spawner:*>);
NEI.hide(<minecraft:spawn_egg:*>);

But the deletion does not happen the first time, for example, when you enter the server or in a singleplayer, the deletion does not happen, although the log says that the deletion was successful. I would like to see support for the crafttweaker in this mod.

**Comment by JaroslawDevmc** [comment]
you can download latest version of nei gtnh and hide all spawner and spawn egg
