### ISSUE TITLE
Trying to put on armor in creative+ mode can't be done though slots, and gets destroyed

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#14]
1) be in C+ mode
2) click armor, click appropriate armor slot
3) armor vanishes

Using NotEnoughItems-1.7.10-2.0.0-beta-6-GTNH-universal.jar in a 2.0.7.5 instance.

**Comment by mitchej123** [comment]
Should be fixed

**Comment by Prometheus0000** [comment]
Which commit/PR fixed it?

**Comment by mitchej123** [comment]
The ticket was for beta 6. Lots of GUI work since then. If it's still an
issue reopen and provide info about which version.  Otherwise I'm assuming
it's fixed since nobody has commented on it.

**Comment by Prometheus0000** [comment]
Works
![image](https://user-images.githubusercontent.com/8517039/103448853-5966fd00-4c6d-11eb-8a55-55a501a7fd81.png)
Does not work
![image](https://user-images.githubusercontent.com/8517039/103448857-5ff57480-4c6d-11eb-88fb-864043041c23.png)
This is the same as before, NotEnoughItems-1.7.10-2.0.6-GTNH-universal.jar

**Comment by mitchej123** [comment]
Haha, turns out I never noticed this because I've got FTBUtilities, which shifts the GUI.  I've also added gameMode() == 2 to the shift.

**Comment by mitchej123** [comment]
Will be fixed in the version with JEI tabs
