### ISSUE TITLE
Interface bug: Main subset bars overlap with items when disabling/enabling items in the sub-subsets

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/NotEnoughItems#15]
Like it says on the tin.
If I click on a specific item in any and all subcategories that happens to overlap with any of the main subsets ("mod"/"blocks""creative tabs" etc), it re-enables the entire subcateogry. 
Here is just one of the many examples I've encountered: GT6 has a ton of item bloat. So I disabled the crucible faucet. I want to only re-enable the ceramic one.
![2020-02-28_20 18 09](https://user-images.githubusercontent.com/5557920/75580229-b0a5ab00-5a67-11ea-8066-df8694118b34.png)
I do so. The moment I re-enable it, the mod thinks I have clicked the subset below it: mod, and destroys fifteen minutes of meticulous NEI filtering. 
![2020-02-28_20 18 28](https://user-images.githubusercontent.com/5557920/75580318-d6cb4b00-5a67-11ea-8238-8c99d58f0aaa.png)

Maybe mirror the subsets on the left, instead of the right? Or add an option to disable the bookmarks bar. 
Thanks.

**Comment by mitchej123** [comment]
The subsets code is not well documented and not very clear as to what does what.  This is an issue, but I'm not clear on a solution so I'm going to punt it to another release; unless someone wants to solve it for me :sunglasses:

**Comment by mitchej123** [comment]
Rather than fighting with it, I'm going to make the subsets only visible when bookmarks are disabled, and have them on the far left of the screen.  This should hopefully solve your issue.  Look for it in beta10+

**Comment by mitchej123** [comment]
Addressed when beta10 is released
