### ISSUE TITLE
NEI can't load the handle message from IMC

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/NotEnoughItems#157]
i can comfirm it still works in 2.1.6 but fails in 2.1.11.
the code at my mod side isn't changed.
[fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/7071800/fml-client-latest.log)

**Comment by GlodBlock** [comment]
the problem lies in here https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/codechicken/nei/recipe/GuiRecipeTab.java#L178
the handles registered from IMC will be cleared, once this line removed the handles from IMC can work well.
but such problem didn't happen in older version, it maybe only the surface of the problem.

**Comment by mitchej123** [comment]
Need to look at the execution order of IMC events vs the general init.  Perhaps add a cache of IMC events to be replayed on handler reload.  Alternatively clear the list before IMC events.
