### ISSUE TITLE
Game startup Crash with CraftingTweaks starting from build 96 (2.1.10) [Fixed in Dev]

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/NotEnoughItems#160]
Hello again. Haven't been playing in a while, I was updating my modpack and realized that craftingtweaks' NEIHotkeyCheck was unerringly crashing my gamewhen loading a world. I tried to reproduce the crash with a barebones instance with only NEI 2.1.11 and CraftingTweaks added, and sure enough it crashed again. When I tested with 2.1.8 (Jenkins build 92) it worked fine.  ̶I̶ ̶h̶a̶v̶e̶ ̶p̶i̶n̶p̶o̶i̶n̶t̶e̶d̶ ̶t̶h̶e̶ ̶c̶r̶a̶s̶h̶ ̶s̶t̶a̶r̶t̶i̶n̶g̶ ̶f̶r̶o̶m̶ ̶b̶u̶i̶l̶d̶ ̶9̶7̶ ̶(̶2̶.̶1̶.̶1̶0̶)̶. 
Edit: After another check, build 96 crashed my game. Since 95 worked fine, https://github.com/GTNewHorizons/NotEnoughItems/commit/dd18d2b77568b32e29ae7e2fb0ed423099634cc7 is the most likely cultprit.

Craftingtweaks' author has long moved to 1.17 and sadly I've got the sinking feeling he doesn't particularly care if his 7 year old product crashes with a very specific unreleased build of a fork of a mod. Could you please look into what happened with that makes it trigger craftingtweaks' hotkey check and crash?

Here is the crashlog (using build 97):https://paste.ee/p/AJnkV

Thank you very much in advance.

**Comment by D-Cysteine** [comment]
Thanks for tracking down the commit that broke this! Sorry, I removed some unused methods in that commit, but didn't realize that there were NEI add-ons which used those methods. The linked PR above adds them back in, and should fix this crash.

**Comment by tyrael93** [comment]
That completely fixed the issue, thank you! :+1: 
I'd close this, but I think I remember being told to wait until the new version of new horizons' release for that, so I'll just add a "fixed in dev" to the name.
