### ISSUE TITLE
BiggerCraftingTables recipe view "borked"

### ISSUE THREAD

**Issue by spannerman79** [GTNewHorizons/NotEnoughItems#167]
Issue;
In recepie view the recipes that can be created using Bigger Crafting Tables overlaps within GTNH build of NEI.  In Chickenbones last version each recipe has its own "page"

An image speaks a thousand words :smile:

![2021-10-20_18 53 18](https://user-images.githubusercontent.com/7542384/138052631-72b7122e-bc55-4e2c-8796-a06cff998e8f.png)

How I _think_ it should be formatted/viewed as;

![2021-10-20_19 03 51](https://user-images.githubusercontent.com/7542384/138053067-953367a7-f737-49ed-9c9c-b1dcf1a82c2d.png)

Mods;
[NotEnoughItems-1.7.10-2.1.12-GTNH-universal.jar](https://www.curseforge.com/minecraft/mc-mods/notenoughitems-gtnh/files/3470838)
[BiggerCraftingTables-1.7.10-1.7.jar](https://www.curseforge.com/minecraft/mc-mods/bigger-crafting-tables/files/2516117)
[WanionLib-1.7.10-1.8.jar](https://www.curseforge.com/minecraft/mc-mods/wanionlib/files/2430662) _Required for BiggerCraftingTables_

**Comment by spannerman79** [comment]
![2021-10-30_16 10 26](https://user-images.githubusercontent.com/7542384/139521106-12cf3820-4d9a-4cd6-acd6-bc07f70680a3.png)

**Comment by mitchej123** [comment]
Should be addressed by https://github.com/GTNewHorizons/NotEnoughItems/commit/0310b4177fca3d2f6c4cb0694828b7fe80359703

**Comment by mitchej123** [comment]
Let me know if the height needs tweaking, I set it to 130 which I hope is sufficient
