### ISSUE TITLE
Not working NEI Hide feature from MineTweaker\Crafttweaker

### ISSUE THREAD

**Issue by xstmas** [GTNewHorizons/NotEnoughItems#17]
Not working NEI Hide feature from MineTweaker\Crafttweaker at latest 1.7.10 version. At original version of NEI is working fine.

Simple scripts for sample:

```
import mods.nei.NEI;

NEI.hide(<ForgeMicroblock:microblock:*>);
```

And that just not working. Don't hide item's. Scripts is only server-side, but locating them locally doesn’t change anything

#Upd I'm test first version of fork - NotEnoughItems-1.7.10-2.0.0-beta-1-GTNH-universal.jar, and that feature is working fine on this build
#Upd2 After restart server, NEI hide feature again not working on beta1 version :). I don't know how it's working.

**Comment by Miradae** [comment]
The NEI hide/override feature of INpureCore (https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2196459-1-7-10-inpure-projects-denoflions-mods) also does not work anymore with -2.0.1-

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by mitchej123** [comment]
[NotEnoughItems-1.7.10-2.0.4-GTNH-universal.zip](https://github.com/GTNewHorizons/NotEnoughItems/files/4706015/NotEnoughItems-1.7.10-2.0.4-GTNH-universal.zip)

@Miradae @xstmas  Please give this a try (rename .zip to .jar)

**Comment by Miradae** [comment]
@mitchej123 it works now, INpure as well as NEI.hide from Minetweaker. THX :)

**Comment by xstmas** [comment]
Yep, works fine. Thx)

**Comment by mitchej123** [comment]
Cool, was a race condition.  Once NEI loaded the items, it never reloaded them.  Before it loaded them _every_ inventory open, which was excessive.  This should strike a nice balance, mark them dirty and reload when needed.
