### ISSUE TITLE
Second Shaped Crafting tab by Storage Drawers

### ISSUE THREAD

**Issue by ThePixelbrain** [GTNewHorizons/NotEnoughItems#170]
**Mod-Version:** NotEnoughItems-1.7.10-2.1.12-GTNH-universal.jar
**Forge-Version:** 1614
**Modpack:** FTB Infinity Evolved Skyblock 2.0.1 ([Modlist on Curseforge](https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved-skyblock/relations/dependencies))

**Issue Description:**
All crafting recipes have a second "Shaped Crafting" tab by Storage Drawers with the exact same content, see the attached screenshot. I would like to get rid of the tab, but I have no idea how to do so.
![v7Cd6_xG](https://user-images.githubusercontent.com/19214217/140048384-5d0979d1-e4f7-4d83-8248-e73b26615dee.png)

**Comment by tyrael93** [comment]
Yeah, that's a storage drawers issue. Here is the mod that fixes it.
https://www.curseforge.com/minecraft/mc-mods/storage-drawers-nei-fix
![fix](https://user-images.githubusercontent.com/5557920/141260585-88be0a2d-1f2b-48a2-8d05-120a2a49fef0.png)

**Comment by ThePixelbrain** [comment]
Great, works like a charm! Thanks for pointing me towards this mod. :)

**Comment by Dream-Master** [comment]
@tyrael93 is this a mod we need in the pack client side ?

**Comment by Glease** [comment]
No. We have fixed this in our fork like 4 years ago.

**Comment by Dream-Master** [comment]
ok
