### ISSUE TITLE
Crash immediately when pressing play

### ISSUE THREAD

**Issue by litten8** [GTNewHorizons/NotEnoughItems#184]
As soon as I press play in any 1.7.10 curseforge instance with the GTNH unofficial NEI, it crashes, saying "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 0"

**Comment by mitchej123** [comment]
Please post a crash log.

**Comment by litten8** [comment]
[latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/7760956/latest.log)

**Comment by mitchej123** [comment]
Make sure you have code chicken core and lib installed.  Also make sure there is only one version of each. Check the mods and the 1.7.10 directory

**Comment by litten8** [comment]
oh, that explains it. I wasn't having the bug for a while, and then started having it when I reorganized the mods in my modpack. I forgot to get codechickencore

**Comment by glowredman** [comment]
@mitchej123 have you set CCC as a required dependency on CurseForge?

**Comment by mitchej123** [comment]
> @mitchej123 have you set CCC as a required dependency on CurseForge?

I believe so.  We've also updated the dependencies.json which I think will fix this.
