### ISSUE TITLE
[Feature Request] Add Search history item panel

### ISSUE THREAD

**Issue by Discreater** [GTNewHorizons/NotEnoughItems#198]
It will be useful to have a search history item panel. 

## Feature Request

1. Add a new item panel (or part of `BookmarkPanel` or `ItemPanel`) part of  to store the search history.
2. Add the item to history panel every time user query usage or recipe.
3. The history should be an queue. But when an existing item is readded, move it to the beginning.
4. Add the configuration options such as max history size or turn off the history.

## NEI Easy Search
In fact, there was already a mod (NEI Easy Search) that did this in Chinese community .
![image](https://user-images.githubusercontent.com/41231596/150755075-eb8e3863-77ab-4c5b-ad08-1d7e7ece8a6c.png)
But this mod only provides two lines of history and cannot be configured. 
**And more importantly**, it **crashed with** NEI-GTNH 2.0. Although I have tried to modify the code to make it work on the NEI 2.0.x and 2.1.x. It still crashed with NEI 2.2. 
This mod uses a lot of reflection, to call or override private methods of `ItemPanel`. Maintaining this mod is difficult (at least for me).

**Comment by vfyjxf** [comment]
> It will be useful to have a search history item panel.
> 
> ## Feature Request
> 1. Add a new item panel (or part of  or ) part of  to store the search history.`BookmarkPanel``ItemPanel`
> 2. Add the item to history panel every time user query usage or recipe.
> 3. The history should be an queue. But when an existing item is readded, move it to the beginning.
> 4. Add the configuration options such as max history size or turn off the history.
> 
> ## NEI Easy Search
> In fact, there was already a mod (NEI Easy Search) that did this in Chinese community . ![image](https://user-images.githubusercontent.com/41231596/150755075-eb8e3863-77ab-4c5b-ad08-1d7e7ece8a6c.png) But this mod only provides two lines of history and cannot be configured. **And more importantly**, it **crashed with** NEI-GTNH 2.0. Although I have tried to modify the code to make it work on the NEI 2.0.x and 2.1.x. It still crashed with NEI 2.2. This mod uses a lot of reflection, to call or override private methods of . Maintaining this mod is difficult (at least for me).`ItemPanel`

Maybe you can try [NEI Utilities](https://github.com/vfyjxf/NEI-Utilities)

**Comment by Discreater** [comment]
@vfyjxf Nice work!

**Comment by vfyjxf** [comment]
> @vfyjxf Nice work!
About the max history size and turn off the history setting, I will add them in recent days.

**Comment by slprime** [comment]
But Items must be align center

With mod             |  Without Mod
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/31038811/166139389-92bcf96e-db26-4713-af82-66b43c417eeb.png) | ![image](https://user-images.githubusercontent.com/31038811/166139398-ec225618-d777-47b9-b111-a1220feca701.png)

**Comment by vfyjxf** [comment]
@slprime Actually, I'm not quite sure what went wrong.

|With Mod | Without Mod | NEI Version |
| :----: | :----: | :----: |
|![image](https://user-images.githubusercontent.com/42764413/166142780-afc228d0-e386-4403-8122-811e732bf1b5.png)| ![image](https://user-images.githubusercontent.com/42764413/166142843-c9d05ef6-4be8-43ae-b6cf-f95df2b8e94c.png) |2.2.10|

**Comment by slprime** [comment]
@vfyjxf  Please use `super.setGridSize(mLeft, mTop, w, h)` in this overwritten method.
![image](https://user-images.githubusercontent.com/31038811/166143598-d9f82f67-f5a5-496c-bd45-76bdad37bab5.png)

In this PR, I've added another computed property to this method
https://github.com/GTNewHorizons/NotEnoughItems/pull/240/files#diff-b21c3be9562bd070e4fe3ec5befb4a01bf23f6dbed66fd13b4f9a4625326fd6fR105

**Comment by vfyjxf** [comment]
OK, I got it.
