### ISSUE TITLE
Bookmarks clip over left side of AE2 interface when in tall mode

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#20]
See above. Reducing the bookmarks by one column would fix this. Dynamically changing it would be better though. Not especially important.

**Comment by mitchej123** [comment]
@repo-alt You're the resident AE2 expert; do you know off the top of your head a good way to see if the AE2 interface is open?  

It's pretty easy to adjust the sizing dynamically, it's already done for a few other things like FTBU

**Comment by repo-alt** [comment]
EntityPlayer.openContainer instanceof AEBaseContainer ?

**Comment by Prometheus0000** [comment]
Still happening in NotEnoughItems-1.7.10-2.0.6-GTNH-universal.jar
![image](https://user-images.githubusercontent.com/8517039/103448875-a9de5a80-4c6d-11eb-9cf9-f83693d4716b.png)

**Comment by mitchej123** [comment]
@Prometheus0000 I think this is fixed, test with the latest beta and reopen if not

**Comment by Prometheus0000** [comment]
With beta3 there's this
![image](https://user-images.githubusercontent.com/8517039/112567648-97307900-8db7-11eb-9a8d-1a3c2ed2bcd9.png)
With the arrow in the upper left clipping over slightly, and the stuff on the right going over the panel a little. The stuff on the right doesn't block anything although it looks bad, so I dunno if you feel it's worth your time to fix. It also does this on the right in non-tall mode too.

**Comment by Skiftcha** [comment]
btw extreme crafting recipes are much better with latest nei
not overlapping anymore
