### ISSUE TITLE
[Feature Request] Setting a custom max width/columns for the item list

### ISSUE THREAD

**Issue by Abalieno** [GTNewHorizons/NotEnoughItems#202]
This problem has annoyed me for a while. Having a huge list of items can cause some lag, and not being very useful.

Scaling the UI works, but I like the rest of the UI scale, I just want to be able to set a max number of NEI items columns so there are less of them.

I've seen people playing with the NEI item list not filling all the space up to the inventory margin on the right, but it might be a newer option on JEI.

So, if there isn't a way to set this up manually in NEI I think it could be an useful feature. Just set a max number of columns, if the space is enough to go above the limit, it stops at the number set. If the space available is smaller then the limit, then just fill the space same as default...

Even better would be to be able to also manually scale the grid itself. Just the rendered blocks, without touching the UI or tooltips.

**Comment by Abalieno** [comment]
Quick blurry screenshot form a random stream, to show what I mean.

This guy is playing with a narrow NEI/JEI item list.

![regrtgrt](https://user-images.githubusercontent.com/4656436/151497262-5d388b67-8676-4f28-af3d-36eb88ae1b35.jpg)

**Comment by miozune** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/pull/240
