### ISSUE TITLE
[question]about high version codechickencore

### ISSUE THREAD

**Issue by creeper263** [GTNewHorizons/NotEnoughItems#220]
How to get codechickencore for above 1.0.9+
The curseforge page just offer 1.0.7.48

**Comment by Glease** [comment]
Get it off maven: http://jenkins.usrv.eu:8081/nexus/content/repositories/public/com/github/GTNewHorizons/CodeChickenCore/
Alternatively, use github release: https://github.com/GTNewHorizons/CodeChickenCore/releases

**Comment by thePalindrome** [comment]
Might be worthwhile putting that in the README.md, since I didn't even realize y'all forked CCC until I found this issue!
