### ISSUE TITLE
About memory checking

### ISSUE THREAD

**Issue by goumo** [GTNewHorizons/NotEnoughItems#222]
![~~TGMLM (V}V2@OO8{)8EQ](https://user-images.githubusercontent.com/76694659/154491489-afdcbc00-0bcc-4ff0-96f9-1ef83da13776.png)
A warning about GTNH should be placed in the GTNH Core Mod, which prevents players from using the mod in other Modpacks.
That could be the reason for CodeChickenCore, but I didn't find the issues entrance there.

**Comment by goumo** [comment]
I just found out that config can change minRAM, but I still think this warning should be changed

**Comment by mitchej123** [comment]
It was placed here given it is one of the first mods to load.  The config was supposed to be off by default.  @bombcar
