### ISSUE TITLE
hidding items from Mekanism

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/NotEnoughItems#233]
I know it's not the focus of the mod, but the mekanism items are disappearing from the NEI, when searching for them they don't appear in the gui
![Screenshot_1](https://user-images.githubusercontent.com/78868186/161665224-0fd4a91b-8175-420b-9b42-a02f7b98e5b9.png)
.

**Comment by miozune** [comment]
Cannot reproduce. Maybe https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9814 ?

![2022-04-05_12 18 21](https://user-images.githubusercontent.com/40035906/161672209-308e3640-3893-45a1-827e-c4dba2a6efcb.png)
