### ISSUE TITLE
[Crash] Thaumcraft + NEI

### ISSUE THREAD

**Issue by BazZziliuS** [GTNewHorizons/NotEnoughItems#264]
Crash when laying out crafting through the "question"

![image](https://user-images.githubusercontent.com/18011884/178109942-6e7b4ef7-3377-4d04-bdb5-895100341419.png)

https://pastebin.com/NxXruUty or [crash-2022-07-09_17.13.31-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/9077314/crash-2022-07-09_17.13.31-client.txt)

NotEnoughItems-1.7.10-2.2.12-GTNH-4-g91e9b2a.dirty
CodeChickenLib-1.7.10-1.1.5.3-1-gc84c687
Thaumcraft-1.7.10-4.2.3.5
OptiFine Version: OptiFine_1.7.10_HD_U_E7
Forge{10.13.4.1614}

**Comment by miozune** [comment]
This cannot be fixed on NEI side. Alternatively you can use [TCNEIAdditions](https://github.com/GTNewHorizons/TCNEIAdditions/tags), which has many bugfixes / new features.
