### ISSUE TITLE
[Crash] NEI

### ISSUE THREAD

**Issue by BazZziliuS** [GTNewHorizons/NotEnoughItems#266]
I watched the crafting of a magic stone and switched to a shapeless Magic Workbench and caught a crash

https://pastebin.com/F9K8NKmA or [crash-2022-07-09_23_39_24-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/9079243/crash-2022-07-09_23_39_24-client.txt)

NotEnoughItems-1.7.10-2.2.12-GTNH-4-g91e9b2a.dirty
CodeChickenLib-1.7.10-1.1.5.3-1-gc84c687
OptiFine Version: OptiFine_1.7.10_HD_U_E7
Forge{10.13.4.1614}

**Comment by miozune** [comment]
It should be able to be reproduced without NEI in certain cases and cannot be fixed on our side
