### ISSUE TITLE
Bookmark incompatibility with Electrobobs's Wizardry

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/NotEnoughItems#267]
**Versions:**
NotEnoughItems-1.7.10-2.2.19-GTNH.jar
Electroblob's Wizardry - 1.1.6 - MC 1.7.10.jar

**Issue:**
Bookmark tab deletes items inserted into the Arcane Workbench on the containers it overlaps:

_Without bookmark tab:_
![Expected](https://user-images.githubusercontent.com/47131096/179048756-0652d76e-e115-4fac-8390-270c40720507.gif)

_With bookmark tab:_
![BookmarProblems](https://user-images.githubusercontent.com/47131096/179053223-67503d6d-ecc4-42ec-8410-88befeae4570.gif)

**Wizardry's GUI class in question:**
https://github.com/Electroblob77/Wizardry/blob/1.7.10/src/main/java/electroblob/wizardry/client/GuiArcaneWorkbench.java

**Comment by DrParadox7** [comment]
This specifically only occurs when a wand is added to the Arcane Workbench which updates the GUI, significantly increasing its width:
![WandInsert](https://user-images.githubusercontent.com/47131096/179238561-37bbb856-71fd-4f32-b4d1-6e61c7f44c0c.gif)

**Comment by mitchej123** [comment]
There is also a method available (forestry uses it) to tell slots not to render because part of an extended GUI is there

**Comment by glowredman** [comment]
Which part specifically needs to be changed? I'll make a PR then.

**Comment by DrParadox7** [comment]
I'd be interested in this too. It'd would be useful to know if an issue like this arises again.

**Comment by mitchej123** [comment]
Here's an example from tinkers: https://github.com/GTNewHorizons/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/gui/CraftingStationGui.java#L275-L292
