### ISSUE TITLE
crash with automagy

### ISSUE THREAD

**Issue by Pa4ok** [GTNewHorizons/NotEnoughItems#272]
crash on showing block cosmetic solid recipe

![image](https://user-images.githubusercontent.com/40999563/185631669-105072b3-e162-4b51-a000-e4c8390512ca.png)

stacktrace 
https://hastebin.com/ahupamaxez.css

**Comment by miozune** [comment]
Duplicate of https://github.com/GTNewHorizons/NotEnoughItems/issues/266. But now I think we can just try-catch the method
