### ISSUE TITLE
Suggestion: allow GT tools, motors, etc. to be used when populating crafting grid

### ISSUE THREAD

**Issue by MauveCloud** [GTNewHorizons/NotEnoughItems#29]
Shift+clicking the "?" icon works to populate the crafting grid with materials for crafting a motor (or a number of other GT items, as long as they use "simple" ingredients), but not when crafting something _with_ the motor, or anything that requires GT tools, like rotors.  As far as I can tell, that is caused by the last condition in this line:
https://github.com/GTNewHorizons/NotEnoughItems/blob/05b5fa7baf4cfc06c60150e4b18991b009bbacb8/src/codechicken/nei/recipe/DefaultOverlayHandler.java#L321
GT Tools use NBT tags to keep track of the materials they were made from as well as durability, so they don't "stack" with the tools shown in the recipe, and I think items like motors, conveyor belts, pumps, and such use tags to allow them to work in the disassembler, but I'm unclear on why the tags need to be strictly checked like this before moving items to the crafting table.  I tried making a local build with the strict NBT tag matching commented out, and with what little testing I've done so far, it seems to work, though idk if that would break something else.

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by mitchej123** [comment]
Cool, thanks for tracking this down.  I don't think we'd want to globally comment out the strict NBT tag matching, but we can make a version that ignores NBT, or select NBT tags, for GT items.

**Comment by draknyte1** [comment]
Checking item class against a cached version of GT tool or item classes was suggested long ago. (Removes dependency against GT and keeps NBT matching for everything else)

Just nobody ever implemented it. 🤷🏻‍♀️

**Comment by Miradae** [comment]
That would be an awesome feature, as it stands currently only forestry craftingtables and AE2 are able to work with GT tools

**Comment by boubou19** [comment]
the removal of the disassembly NBT should partially adress this for the GT components.

**Comment by Miradae** [comment]
> the removal of the disassembly NBT should partially adress this for the GT components.
But that is still something that has to be done in the source code, right? It's nothing we can do on user side?

**Comment by mitchej123** [comment]
This should be in beta 15 or so.  Please test it out and let me know if you find any issues with it; it worked in my limited testing.
