### ISSUE TITLE
Not Enough Resources issue

### ISSUE THREAD

**Issue by xJon** [GTNewHorizons/NotEnoughItems#295]
Hi!
Is there any chance your NEI fork could prevent this NER crash? https://mclo.gs/ug4YImL
Thanks :)

**Comment by mitchej123** [comment]
Added a try/catch; no guarantees returning a null won't break other assumptions.  It looks like NER might be available and could be fixed there - https://github.com/hilburn/NotEnoughResources/blob/master/LICENSE.md

**Comment by xJon** [comment]
That seems to have resolved it! Thanks :)
