### ISSUE TITLE
Suggestion: add NBT support for different bookmarks

### ISSUE THREAD

**Issue by GedeonGrays** [GTNewHorizons/NotEnoughItems#30]
_Hello o/
I apologize in advance for my English._

**What exactly do I need:** just the ability to create bookmarks for the same item ID, but with different NBTs.

**For example:** if I want to lay a bookmark with two diamond swords, but with different enchantments. Or I need to have bottles of Thaumcraft essence on hand. Or even I just need to save a written book with important information so that I never lose it.

_P.S. I hope that something can be done about it. But in any case, thanks for your time._

**Comment by dvdmandt** [comment]
This is something I'd love to see as well. In my case, I've often found myself wanting to compare stats of different materials in stuff like weapons, rotors or prospectors with respect to what materials I currently have on hand or can make within a reasonable time frame.

**Comment by GedeonGrays** [comment]
> This is something I'd love to see as well. In my case, I've often found myself wanting to compare stats of different materials in stuff like weapons, rotors or prospectors with respect to what materials I currently have on hand or can make within a reasonable time frame.

Yes, there are actually more reasons than I have described. I think that everyone has a couple of their own ideas on how to use this functionality.
