### ISSUE TITLE
NEI Bookmarks Animation

### ISSUE THREAD

**Issue by slprime** [GTNewHorizons/NotEnoughItems#304]
Version: NotEnoughItems-1.7.10-2.3.7-GTNH

Please disable animation if change items count in bookmarks:
https://user-images.githubusercontent.com/31038811/193314994-8ec5cc9a-c849-4942-9c9d-06217f4681d8.mp4

**Comment by slprime** [comment]
and sometimes added this item
![image](https://user-images.githubusercontent.com/31038811/193402533-aa5e61d7-a689-4136-a92d-cfa77ac90ef6.png)

**Comment by Abalieno** [comment]
Also reporting that enabling rendering cache in options causes a problem with the default animation of bookmarks, because it renders the first frame only, and so essentially an empty bookmark.
