### ISSUE TITLE
dragon api and nei compat

### ISSUE THREAD

**Issue by jrslwstark** [GTNewHorizons/NotEnoughItems#305]
crashing when i'm take items from nei when dragon api installed.

**Comment by mitchej123** [comment]
Please provide a crashlog.  We'll take a look; but warning - I'm not sure how much support we'll be able to provide for DragonAPI given the invasive ASM it uses.

**Comment by jrslwstark** [comment]
Can i do it tommorow im busy now

**Comment by jrslwstark** [comment]
here is my problem
[crash-2022-10-04_17.03.56-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/9706514/crash-2022-10-04_17.03.56-client.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/9706516/fml-client-latest.log)

**Comment by miozune** [comment]
This is due to recent incompatible change (https://github.com/GTNewHorizons/NotEnoughItems/commit/6d9ec0c0da3551ac31e28ff10edfd01a4a6342be#diff-49f5e89168557e51486641c6f9311c2202dd2fa4c81471956044a7f484c64db2R18).
@Quarri6343 Is it possible to keep backward compatibility?

**Comment by slprime** [comment]
That PR broke this too:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11531
https://github.com/GTNewHorizons/NotEnoughItems/issues/304

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/307
