### ISSUE TITLE
NEI crashes Recipe Packager from Buildcraft

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/NotEnoughItems#310]
**Mods used:**
NotEnoughItems-1.7.10-2.3.9-GTNH.jar
CodeChickenCore-1.7.10-1.1.6.jar
buildcraft-7.1.24.jar

**What happens:**

Hovering over Packages made by BC's Recipe Packager crashes the game:
![image](https://user-images.githubusercontent.com/47131096/196035460-a4a9a882-cdce-471b-8833-4f14c846d2c5.png)

> Description: Rendering screen

> java.lang.NumberFormatException: For input string: "r"
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:580)
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at [buildcraft.silicon.render.PackageFontRenderer.func_85187_a(PackageFontRenderer.java:40)](https://github.com/BuildCraft/BuildCraft/blob/cc1893448c3251df94383559ba164dbd49a1894e/common/buildcraft/silicon/render/PackageFontRenderer.java#L40)
> 	at net.minecraft.client.gui.FontRenderer.func_78261_a(FontRenderer.java:253)
> 	at [codechicken.lib.gui.GuiDraw.drawMultilineTip(GuiDraw.java:200)](https://github.com/GTNewHorizons/CodeChickenLib/blob/23327451a26c6732d336521320f3f3ebdc94347e/src/main/java/codechicken/lib/gui/GuiDraw.java#L200)
> 	at [codechicken.nei.guihook.GuiContainerManager.renderToolTips(GuiContainerManager.java:500)](https://github.com/GTNewHorizons/NotEnoughItems/blob/4b4ab434c05a0a55e56ef1f80fa5efe231eea7a9/src/main/java/codechicken/nei/guihook/GuiContainerManager.java#L500)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
> 	at [buildcraft.core.lib.gui.GuiBuildCraft.func_73863_a(GuiBuildCraft.java:75)](https://github.com/BuildCraft/BuildCraft/blob/cc1893448c3251df94383559ba164dbd49a1894e/common/buildcraft/core/lib/gui/GuiBuildCraft.java#L75)

**Full Crash Report:**
https://pastebin.com/Tm1Qvq4m

**Comment by DrParadox7** [comment]
I made Buildcraft print out  the string causing problems in PackageFontRenderer.java:40:

**Before:**
[14:43:23] [Client thread/INFO] [STDOUT]: [buildcraft.silicon.render.PackageFontRenderer:drawString:39]: string: �7SPECIAL:0
**After:**
[Client thread/INFO] [STDOUT/]: [buildcraft.silicon.render.PackageFontRenderer:drawString:39]: string: �7SPECIAL:0�r

**Comment by DrParadox7** [comment]
@slprime The formatting code used here is likely the culprit:
https://github.com/GTNewHorizons/NotEnoughItems/commit/fb9d517f78cf85259fcbbbf7f2fd1bbb76b2abc6

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/8a6b1267015443a28b060ef6d1b39a6178a2d2d0
