### ISSUE TITLE
Crash with arcane worktable

### ISSUE THREAD

**Issue by PBegkas** [GTNewHorizons/NotEnoughItems#32]
I am on version 2.1.0.0.
At 2 separate occasions I tried to shift click a recipe into the arcane worktable from thaumcraft and the client crashed.
After logging back in the arcane worktable had some of the items inserted.

[crash-2020-12-30_20.25.27-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/5759361/crash-2020-12-30_20.25.27-client.txt)
[crash-2021-01-01_21.37.52-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/5759362/crash-2021-01-01_21.37.52-client.txt)

**Comment by huaz95** [comment]
> I am on version 2.1.0.0.
> At 2 separate occasions I tried to shift click a recipe into the arcane worktable from thaumcraft and the client crashed.
> After logging back in the arcane worktable had some of the items inserted.
> 
> [crash-2020-12-30_20.25.27-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/5759361/crash-2020-12-30_20.25.27-client.txt)
> [crash-2021-01-01_21.37.52-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/5759362/crash-2021-01-01_21.37.52-client.txt)

**Comment by mitchej123** [comment]
Added an attempted fix, will be in the next beta.
