### ISSUE TITLE
Using GTNH blood magic with NEI build crash when viewing a recipe

### ISSUE THREAD

**Issue by ilkerbey-01** [GTNewHorizons/NotEnoughItems#331]
When pressing R to view any recipe game crashes in singleplayer.
Crash Report: https://hastebin.com/yejafamiju.yaml

**Comment by ilkerbey-01** [comment]
[latest.log (2).txt](https://github.com/GTNewHorizons/NotEnoughItems/files/10394952/latest.log.2.txt)

**Comment by mitchej123** [comment]
You're using the GTNH version of Blood Magic, but not the GTNH version of NEI; this is incompatible.  Please try again with a recent GTNH NEI release - https://github.com/GTNewHorizons/NotEnoughItems/releases

```
UCHIJAAAA	AWWayofTime{1.3.20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.20.jar) 
UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
```

**Comment by ilkerbey-01** [comment]
I am sorry about that :p my friend was testing what I told him but apperantly he skipped a step.
