### ISSUE TITLE
Nei Integration freeze game

### ISSUE THREAD

**Issue by Fabboz** [GTNewHorizons/NotEnoughItems#35]
After entering the world pressing U to see used recipe of an item in inventory  the game freeze and then windows say the application is not responding.
Instead pressing R all works and U works again.

**Comment by Fabboz** [comment]
Also with onlu Forestry lastet commit GTNH fork.

**Comment by Fabboz** [comment]
before commit [https://github.com/GTNewHorizons/NotEnoughItems/commit/c2acfb7d8a7f457e5d50c551ffc94f28f12a315b](url) 
seems to work better.

**Comment by mitchej123** [comment]
Resolved, grab 2.0.9

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/NEI/30/
