### ISSUE TITLE
F7 light level not working correctly.

### ISSUE THREAD

**Issue by alonegreen** [GTNewHorizons/NotEnoughItems#361]
Its somehow misses some spots.
Here the proof and shows what i mean.
![lightlevel](https://user-images.githubusercontent.com/50367987/222977704-e66de468-3052-490e-80bf-78fcd99f182e.png)

**Comment by chochem** [comment]
what is your version? there were some fixes recently.

**Comment by alonegreen** [comment]
Im using NotEnoughItems-2.3.38-GTNH

**Comment by eigenraven** [comment]
Can you try 2.3.32 to see if it works there? Just to see if it was my changes that broke something or an old bug.

**Comment by alonegreen** [comment]
I am using NotEnoughItems-2.3.38-GTNH

**Comment by alonegreen** [comment]
> Can you try 2.3.32 to see if it works there? Just to see if it was my changes that broke something or an old bug.

I tryed it and it same result

**Comment by eigenraven** [comment]
Can you show your F3 screen? And what is the dimension you're in? Overworld, personal space or something else?

**Comment by alonegreen** [comment]
> Can you show your F3 screen? And what is the dimension you're in? Overworld, personal space or something else?

sure im in overworld (Using 2.3.32)
![f3show](https://user-images.githubusercontent.com/50367987/222978237-92a4547a-8d52-43c7-bf4a-8ce6a46d356b.png)

**Comment by alonegreen** [comment]
I know what the problem is.
It is chisel blocks.

**Comment by alonegreen** [comment]
Its a bug in chisel.
The new chisel that you made has this bug.
The old chisel works fine so its not a nei bug sorry

**Comment by mitchej123** [comment]
It's not a bug, it's a feature 
<img width="770" alt="image" src="https://user-images.githubusercontent.com/1894689/223026329-d229370e-f67d-45ca-8147-ac8c9e07261f.png">


Also it doesn't show lightlevel, it shows if a mob can spawn there.
