### ISSUE TITLE
[Feature Request]Backport EMI Recipe Tree

### ISSUE THREAD

**Issue by NaCa1814** [GTNewHorizons/NotEnoughItems#373]
EMI Mod:[https://modrinth.com/mod/emi](url)
Recipe Tree could show how many base ingredients we need to make machines,which makes it easier to finish a task.

**Comment by joshaup1999** [comment]
Something like that is coming to AE, apart from that if you want something similar just download not enough calculators or whatever its called

**Comment by bombcar** [comment]
https://github.com/Towdium/JustEnoughCalculation/tree/1.7.10 has been looked at for inclusion in GT:NH, and it works, so it's unlikely that a similar feature would be added to NEI itself
