### ISSUE TITLE
[BUG] Bug with my large modpack since "NotEnoughItems-2.3.48-GTNH" 

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/NotEnoughItems#380]
Can be fixed by downgrading NEI to NotEnoughItems-2.3.47-GTNH

Crash when try to join second time a world(ON SERVER) : 
[crash-2023-05-10_19.27.30-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/11444605/crash-2023-05-10_19.27.30-client.txt)

the modpack : 

https://legacy.curseforge.com/minecraft/modpacks/biggess-pack-cat-edition/files/4521827

**Comment by Ydrec** [comment]
This is a hardpass to support, that pile up of mods has some invasive mods, mods which purposefully don't work with gtnh codebase and a lot of conflicting and poorly written mods.

Do some diligence and find which mod causes conflict at least. Better if you can point at which change between NEI 47 and 48 caused that to conflict.

**Comment by quentin452** [comment]
i maked alot of test , and every time i make a new test , it seem that not same mods are suspects , so i think its a bug in NEI

**Comment by quentin452** [comment]
i tried the latest 2.3.51 but didn't work , only work with 2.3.47 and before

**Comment by wlhlm** [comment]
This is a specially modified version.

**Comment by quentin452** [comment]
normally i have a crash report with 2.3.51 i will give you

**Comment by wlhlm** [comment]
This will not be helpful. Again, the jar I've linked to above has a couple of additional log messages, that might help me narrow this down.

**Comment by quentin452** [comment]
[crash-2023-05-10_16.15.29-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/11445109/crash-2023-05-10_16.15.29-client.txt)

**Comment by Ydrec** [comment]
Use that special given version, it was modified to provide more debug information on the crash form nei side. Its not the same as normal . 51

**Comment by quentin452** [comment]
ah ok

**Comment by wlhlm** [comment]
Also, I need the full client log not just the crash log. The crash log does not have all the information I need.

**Comment by quentin452** [comment]
i just need to change the Nei version to this version right?

![Capture d’écran_2023-05-10_20-56-53](https://github.com/GTNewHorizons/NotEnoughItems/assets/42176772/da7163c3-5e0f-492e-9b06-cb45123f624f)

**Comment by quentin452** [comment]
ok so l'ill try it , and i will give you crash report + fml-client-latest.log

**Comment by quentin452** [comment]
Here is the crash report + logs with the debug

[crash-2023-05-10_21.03.35-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/11445153/crash-2023-05-10_21.03.35-client.txt)

[fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/11445160/fml-client-latest.log)

**Comment by wlhlm** [comment]
Thank you, that was very helpful. I think I have a fix. Can you please try the following jar (within the zip file) and let me know if it fixes the crash?

[NotEnoughItems-2.3.51-GTNH.bigpack.fix-1.zip](https://github.com/GTNewHorizons/NotEnoughItems/files/11445374/NotEnoughItems-2.3.51-GTNH.bigpack.fix-1.zip)

**Comment by quentin452** [comment]
I am starting the game, let's wait

**Comment by quentin452** [comment]
it seem the same crash occur

**Comment by quentin452** [comment]
wait , its seem that fixed it , i crashed and i tried to rejoin the server and seem to be work. so idk

**Comment by wlhlm** [comment]
Hmm, that doesn't give me a lot of confidence. Can you maybe try booting the server and client fresh? Make sure you have the latest jar that I've posted above installed in your client instance (`.bigpack.fix-1.jar`). Then connect to the server once and then a second time.

If it crashes on the first connect, please post that here anyway, It may not be related to this bug report, but I still want to make sure that it isn't related to some other issue in NEI... With 800 mods, you can expect things to be weird.

**Comment by wlhlm** [comment]
I mean just stopping both client and server and starting them again.

**Comment by quentin452** [comment]
i have the **.bigpack.fix-1.jar** in both

1 : i relanched both

2 : first time joining server world , all is okay

3 : second time joining server world , all is okay

4 : some time joining server world , all is okay


to make sure that isn't chance , i will relaunch again server and client

**Comment by quentin452** [comment]
Test 2 : 

i have the .bigpack.fix-1.jar in both

1 : i relanched both

2 : first time joining server world , all is okay

3 : second time joining server world , crash : 
[crash-2023-05-10_22.13.26-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/11445638/crash-2023-05-10_22.13.26-client.txt)

4 : some time joining server world , all is okay

So its better than before , like just one crash , not all time crash when try to join server world

**Comment by wlhlm** [comment]
OK, so it's still the same issue. Can you please upload the full client log?

**Comment by wlhlm** [comment]
OK, here is my second attempt at a fix. Please try!

[NotEnoughItems-2.3.51-GTNH.bigpack.fix-2.zip](https://github.com/GTNewHorizons/NotEnoughItems/files/11445924/NotEnoughItems-2.3.51-GTNH.bigpack.fix-2.zip)

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
So i relaunched two times client and server and maked test , and it seem that crash is fixed.Thx.

**Comment by wlhlm** [comment]
Great to hear. A proper NEI release with the fix will hopefully be released soon.

**Comment by quentin452** [comment]
ok Thx
