### ISSUE TITLE
`recipiesPerPage()` gets ignored and the mod attempts to combine pages that can't be combined

### ISSUE THREAD

**Issue by Roadhog360** [GTNewHorizons/NotEnoughItems#386]
I have this NEI recipe handler set to ONE per page, this works in default NEI but GTNH NEI seems to ignore it and tries to merge pages that are not meant to be merged, causing a badly glitched result.

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/11903511/cbbb696f-4752-40c9-b709-74921ebf661d)

# Expected result:
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/11903511/ab2d1005-5a23-4b20-b67b-7820f5873a77)

**Comment by wlhlm** [comment]
Hi, sorry for the late response.

Is this mode publicly available. Can you post a link so that I can test this on my side?

**Comment by Roadhog360** [comment]
> Hi, sorry for the late response.
> 
> Is this mod publicly available. Can you post a link so that I can test this on my side?

The mod is called Et Futurum Requiem and this happens on the beta build, found in actions tab in my GitHub.

**Comment by wlhlm** [comment]
Looks like you are forcing `maxRecipesPerPage` to 5 via IMC:

https://github.com/Roadhog360/Et-Futurum-Requiem/blob/0bf1b2342d34cced4ed6171904cd409d4812fdb7/src/main/java/ganymedes01/etfuturum/compat/nei/IMCSenderGTNH.java#L45
