### ISSUE TITLE
Recipe mode broken in 2.3.57

### ISSUE THREAD

**Issue by kutschkem** [GTNewHorizons/NotEnoughItems#396]
No matter what mode I select (recipe, utility, cheat), NEI behaves as if in  cheat mode. Specifically, I can give myself items.

The world has cheats enabled, gamemode is survival. Version 2.3.57.

**Comment by vovaksenov** [comment]
I would imagine this is outdated and can be closed.

**Comment by Dream-Master** [comment]
@kutschkem use a newer version and test agian.

**Comment by kutschkem** [comment]
@Dream-Master I tested again with 2.5.17 and I found that when I Ctrl-Click on the wrench to change the mode, it does change the mode as expected. But changing it in the settings page is broken, it does nothing:

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/1106888/adb2709d-af01-4853-8521-e7a48fde7fd5)

I think this might also be the root cause for the problem I had with 2.3.57, I don't think I changed modes with the Ctrl-Click method then.
Please reopen the ticket, I can change the title to something more useful then.

**Comment by vovaksenov** [comment]
> @Dream-Master I tested again with 2.5.17 and I found that when I Ctrl-Click on the wrench to change the mode, it does change the mode as expected. But changing it in the settings page is broken, it does nothing:
> 
> ![image](https://private-user-images.githubusercontent.com/1106888/303421529-adb2709d-af01-4853-8521-e7a48fde7fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MTYyNjcsIm5iZiI6MTcwNzQxNTk2NywicGF0aCI6Ii8xMTA2ODg4LzMwMzQyMTUyOS1hZGIyNzA5ZC1hZjAxLTQ4NTMtODUyMS1lN2E0OGZkZTdmZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTgxMjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzYyOWUwYmNmZjk0MGVlZjk3NmQ5ZGRhNmUzNWJhNmJiN2MzZGQyNzkwYWY5ZTM4YjI4MWQ0ZWVmODRiNmUwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8WnIwO46ziYHk9B7fY1T7-120vHhue15GLa0dVgm2R0)
> 
> I think this might also be the root cause for the problem I had with 2.3.57, I don't think I changed modes with the Ctrl-Click method then. Please reopen the ticket, I can change the title to something more useful then.

You have global settings selected on the top right. These only work if world settings do not override them (they usually do). Change the mode to "world" by clicking on the "global" button and everything will work.

**Comment by kutschkem** [comment]
@vovaksenov Thanks, that works! Whenever I go to that screen it uses the global one by default. Is there a way to make the default the world specific one?

**Comment by vovaksenov** [comment]
@kutschkem i dont think there is but i am not 100% sure. Try looking through the settings and config or ask on the gtnh discord.
