### ISSUE TITLE
NEI does not work at all

### ISSUE THREAD

**Issue by numba1placekfan** [GTNewHorizons/NotEnoughItems#400]
~removed~

**Comment by numba1placekfan** [comment]
oops wrong place

**Comment by numba1placekfan** [comment]
im retarded this is the right place

**Comment by numba1placekfan** [comment]
the problem still persists after switching to an entirely different modpack and updating my java

**Comment by vovaksenov** [comment]
You should be able to get faster help if you join the gtnh discord server.

**Comment by mitchej123** [comment]
@numba1placekfan Please do not post logs with inappropriate paths or worldnames in them.
