### ISSUE TITLE
Odd Crash Regarding codechicken/multipart/BlockMultipart

### ISSUE THREAD

**Issue by Cicopath** [GTNewHorizons/NotEnoughItems#412]
I'm experiencing some odd crash I'm not familiar with. I'm not familiar with 1.7.10; this is my first time with the version. I'll do some more tests to see if a specific mod is causing it.

I'm using NEI GENT 2.3.81, CodeChickenCore 1.1.11, and CodeChickenLib 1.1.8.

[crash-2023-08-15_16.50.35-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/12352934/crash-2023-08-15_16.50.35-client.txt)

**Comment by Cicopath** [comment]
Nevermind, it has to do with Mekanism and an outdated Forge Multipart lol.

**Comment by Cicopath** [comment]
However, now I have a new issue: I can't use the JEI integrations from NEI Unofficial because it requires CodeChickenCore Unofficial, and I need to use the original CodeChickenLib for Forge Multipart for Mekanism. The two cores are duplicates, essentially.

**Comment by boubou19** [comment]
can't you just use our forge multipart instead? https://github.com/GTNewHorizons/ForgeMultipart/releases/tag/1.3.4
