### ISSUE TITLE
Latest NEI doesnt work with CraftTweaker (both from GTNH)

### ISSUE THREAD

**Issue by Prooty** [GTNewHorizons/NotEnoughItems#415]
list of mods:
CraftTweaker-3.2.13
NotEnoughItems-2.3.82-GTNH
ContentTweaker-1.0.5
ModTweaker2-0.9.10
CodeChickenLib-1.1.8
CodeChickenCore-1.1.11
Fluxed-Core-MC1710-1.0.9

zs script:
import mods.nei.NEI.hide;
import minetweaker.item.IItemStack;

NEI.hide(<minecraft:stone>);

[fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/12412829/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/GTNewHorizons/NotEnoughItems/files/12412830/fml-junk-earlystartup.log)
[latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/12412831/latest.log)
[minetweaker.log](https://github.com/GTNewHorizons/NotEnoughItems/files/12412832/minetweaker.log)

**Comment by miozune** [comment]
Shouldn't it be
```
import mods.nei.NEI;
NEI.hide(<minecraft:stone>);
```
?
Also this is not about NEI but CT.
