### ISSUE TITLE
[BUG] Pull all bookmarked items from storage to inventory not works with iron chests

### ISSUE THREAD

**Issue by Darkenlord1** [GTNewHorizons/NotEnoughItems#423]
Pull all bookmarked items from storage to inventory feature does not work with chests from iron chests.

GTNH version 2.4.0

**Comment by Nilau1998** [comment]
The logic isn't implemented for Iron Chests yet sadly. The new version 2.4.1 will hide this feature for containers/guis that don't support it to prevent the confusion.

Sorry for not being able to provide it yet.

**Comment by Darkenlord1** [comment]
It's alright, thank you all for hard work on the modpack! Looking to the next updates!
