### ISSUE TITLE
Allow bookmarks to overlap potion effects optionally

### ISSUE THREAD

**Issue by Star-Tube** [GTNewHorizons/NotEnoughItems#424]
Here is an example of what my bookmarks look like given a big job planning out a fair few crafts. I was hoping there might be a way to have an option allowing the bookmarks to ignore the potion effects.
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/50463083/01a21431-479c-4ecf-9b9d-6e424a9b5325)

It seems like this functionality was default a while ago and was changed [here](https://github.com/GTNewHorizons/NotEnoughItems/issues/231). If possible, making a toggle so people with permanent effects can not have that chunk forever taken out of the bookmarks panel would be nice.

**Comment by vovaksenov** [comment]
It already exists: Nei options > inventory > ignore overlap with potion effect HUD.
