### ISSUE TITLE
[FEATURE REQUEST] [?] button compatibility for non-crafting-table recipes

### ISSUE THREAD

**Issue by HanakoU235** [GTNewHorizons/NotEnoughItems#428]
As the title says, theres some recipes in various mods that dont use the crafting table, but another method of crafting (Hammers mod, HBM, NTM, etc.)

The button i propose would be used for getting all the materials directly placed onto your inventory. This would cut off several seconds of searching through your storage system and getting the items one by one, such as the ME System, crates, chests, or whatever else. To visualize it better, lets say a recipe asks for 10 different components placed on a special tile entity which uses Energy or Magic or whatever. Instead of searching on your ME system for all of the 10 components, you could just go to the main recipe, click a [?] button, and get all the necessary items avaliable directly in your inventory. 

Thats it all

**Comment by miozune** [comment]
NEI just provides API to overlay recipes, but not have compatibility with other mods. Each mod needs to implement `IOverlayHandler` and `IRecipeOverlayRenderer`.
It's out of the scope of this mod, please ask the author of the mods you want to have compatibility.

**Comment by awbarr** [comment]
I wanted to comment that OP asked for another button designed specifically to retrieve the items necessary for the recipe, not overlay the items automatically like it does with crafting. For instance, if the anvil required a special table to craft, you would open your ME system/chest/backpack, open the recipe, click the button to "grab" the exact components necessary and put them in your inventory, then you would assemble the part.

**Comment by miozune** [comment]
Oh I see. I think it's too complicated to implement, but I'd leave this issue opened in case someone else is interested in.

**Comment by Nilau1998** [comment]
I implemented that more or less already, you can bookmark a recipe with Ctrl-Shift-A when looking at it and hovering over the product. Newer versions now provide a new button at the bottom left labeled "P" that pulls items out of the currently opened container, if the container is supported by the feature. Hotkey V works too to pull what's bookmarked. Supported so far are vanilla chests, iron chests, compressed chests, ME terminals, TiCo crafting stations connected to containers.

You can close that from my perspective @miozune
