### ISSUE TITLE
I can't use the U and R keys

### ISSUE THREAD

**Issue by manskyn** [GTNewHorizons/NotEnoughItems#431]
I can't use the R and U keys, please help me

**Comment by miozune** [comment]
- Check your keybind. Not on MC keyconfig, but NEI has its own config.
- If keybinds are set correctly, post your modpack or modlist.

**Comment by manskyn** [comment]
I tested what you said but it didn't work
https://www.mediafire.com/file/wnxhmdseauifehf/modpack.zip/file

**Comment by manskyn** [comment]
and I've also updated the mod now but the problem still persists

**Comment by manskyn** [comment]
ae2stuff-0.5.7-GTNHjar
AgriCraft-1.7.10-1.5.0.jar
appliedenergistics2-v3-beta-237-GTNH.jar
Avaritia-1.46.jar
Avaritiaddons-1.5.5-GTNH.jar
bdlib-1.7.10-1.9.8-GTNH.jar
Better-Furnaces-Mod-1.7.10.jar
BetterFps-1.0.1.jar
BigReactors-0.4.3A.jar
Botania+r1.8-249.jar
BrandonsCore-1.0.0.12.jar
chisel-2.11.4-GTNH.jar
CodeChickenCore-1.1.11.jar
CoFHCore-[1.7.10]3.1.4-329.jar
Craft Tweaker-3.2.12.jar
CustomThings-MC1.7.10-0.0.3-52.jar
Draconic-Evolution-1.7.10-1.1.7-GTNH.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
EnderCore-1.7.10-0.2.0.40_beta.jar
Ender10-1.7.10-2.3.0.429_beta.jar
EnderlOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta.jar
EnderStorage-1.7.10-1.4.12.jar
EternalSingularity-1.7.10-1.0.4b.jar
extrautilities-1.2.13a.jar
FpsReducer-mc1.7.10-1.10.3.jar
GardenOfGlass.jar
Hardcore Wither-1.7.10-1.1.3-21-universal.jar
industrialcraft-2-2.2.828a-experimental.jar
IndustrialUpgrade-2.5.21.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.2 1.7.10.jar
magicalcrops-4.0.0_PUBLIC_BETA 5.jar
Mantle-0.3.7.jar
mcjtylib-1.7.0.jar
Mekanism-Core.jar
Mekanism-Generators.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
Mouse Tweaks-2.4.9-GTNH.jar
No-More-Recipe-Conflict-Mod-1.7.10.jar
NotEnoughEnergistics-1.4.2.jar
NotEnoughItems-2.4.5-GTNH.jar
OpenBlocks-1.7.10-1.6.jar
OpenModsLib-1.7.10-0.10.jar
OptiFine_1.7.10_HD_U_E7.jar
p455w0rdslib-1.7.10-1.0.4.jar
ProjectE-1.7.10-PE1.10.1.jar
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
QuantumFlux-1.7.10-1.3.4.jar
ResourceLoader-MC1.7.10-1.3.jar
rftools-4.01.jar
roguelike-1.7.10-1.5.3-GTNH.jar
StorageDrawers-1.7.10-1.10.8.jar
TConstruct-1.10.5-GTNH.jar
Thermal Dynamics-[1.7.10]1.2.1-172.jar
ThermalExpansion-[1.7.10]4.1.5-248.jar
Thermal Foundation-[1.7.10]1.2.6-118.jar
TiConAuto ToolStation-1.7.10-1.1.2.jar
TICTooltips-mc1.7.10-1.2.5.jar
TMechworks-1.7.10-0.2.15.106.jar
Translocator-1.7.10-1.1.2.16-universal.jar
TwilightForest-2.4.3.jar
Universal Singularities [Version 8]-1.7.10.jar
WailaHarvestability-1.7.10-1.1.10-GTNH.jar
WAILAPlugins-1.7.10-0.2.5.jar
WanionLib-1.7.10-1.8.2.jar
Wawla-1.7.10-1.1.3-GTNH.jar
WirelessCrafting Terminal-1.7.10-rv3-1.8.7.4b.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
Xaeros-Minimap-Mod-1.7.10.jar

**Comment by Caedis** [comment]
What color is the icon in the bottom left of the screen when NEI is open?

**Comment by manskyn** [comment]
I removed all the mods and left just not enoughitems and it worked normally, but when I added all the mods it stopped

**Comment by Caedis** [comment]
Ah, definitely a keybind conflict then

**Comment by manskyn** [comment]
> Qual é a cor do ícone no canto inferior esquerdo da tela quando o NEI está aberto?

White

**Comment by manskyn** [comment]
> Ah, definitivamente um conflito de teclas então

But I removed all the keys in the config

**Comment by Caedis** [comment]
There are some mods (like NEI) that do not show up in the main config keybind screen.

What happens if you change the Show Recipe button to F1 instead of R?

**Comment by manskyn** [comment]
> Existem alguns mods (como NEI) que não aparecem na tela principal de configuração do teclado.
> 
> O que acontece se você alterar o botão Mostrar receita para F1 em vez de R?
I'll do a test.

**Comment by manskyn** [comment]
> Existem alguns mods (como NEI) que não aparecem na tela principal de configuração do teclado.
> 
> O que acontece se você alterar o botão Mostrar receita para F1 em vez de R?
Test this up to F2 and F3, it still didn't work

**Comment by manskyn** [comment]
Example  I want to see the Craft table recipe but when I click on the wood recipe, it doesn't work like R & U

**Comment by Caedis** [comment]
Time to start dividing your mod list into 2 and see if the issue persists.

Split your mod list  in 2, and pick either set and disable them. Does the issue persist? Repeat
If not, the issue mod was in the disabled list. Repeat the above line on that list

**Comment by manskyn** [comment]
> É hora de começar a dividir sua lista de mods em 2 e ver se o problema persiste.
> 
> Divida sua lista de mods em 2 e escolha defini-los e desativá-los. O problema persiste? Repita , caso contrário, o mod do problema estava na lista de desativados. Repita a linha acima nessa lista

I did this by dividing everyone into exits and entering with all the mods , everything was compatible with Nei but when I put all the mods back on, it still had the problem :(

**Comment by manskyn** [comment]
I'm already getting discouraged :(

**Comment by Caedis** [comment]
Is this a custom pack?

**Comment by mitchej123** [comment]
You'll need to provide a fml client latest.log

**Comment by manskyn** [comment]
> Você precisará fornecer um cliente fml last.log

[latestlog.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/13060158/latestlog.txt)
Aqui está

**Comment by manskyn** [comment]
> Você precisará fornecer um cliente fml last.log

content://ru.zdevs.zarchiver.external/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt
Aqui está.

**Comment by manskyn** [comment]
> You'll need to provide a fml client latest.log

![latestlog.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/13060192/latestlog.txt)

**Comment by manskyn** [comment]
> Is this a custom pack?

Yes

**Comment by mitchej123** [comment]
```
Exception in thread "NEI Plugin Loader" [04:30:43] [NEI Plugin Loader/INFO]: 

 java.lang.IllegalAccessError: tried to access field fox.spiteful.avaritia.compat.botania.ItemInfinitatoCostume.types from class fox.spiteful.avaritia.compat.nei.NEIAvaritiaConfig
  at fox.spiteful.avaritia.compat.nei.NEIAvaritiaConfig.loadConfig(NEIAvaritiaConfig.java:27)
  at codechicken.nei.NEIClientConfig$8.run(NEIClientConfig.java:497)
```

This is the only exception that seems remotely related.

**Comment by manskyn** [comment]
> ```
> Exception in thread "NEI Plugin Loader" [04:30:43] [NEI Plugin Loader/INFO]: 
> 
>  java.lang.IllegalAccessError: tried to access field fox.spiteful.avaritia.compat.botania.ItemInfinitatoCostume.types from class fox.spiteful.avaritia.compat.nei.NEIAvaritiaConfig
>   at fox.spiteful.avaritia.compat.nei.NEIAvaritiaConfig.loadConfig(NEIAvaritiaConfig.java:27)
>   at codechicken.nei.NEIClientConfig$8.run(NEIClientConfig.java:497)
> ```
> 
> This is the only exception that seems remotely related.



What do I do now? Do you have any tips for trying to solve the problem?

**Comment by manskyn** [comment]
There are other mods that don't have an example recipe for ender io e ThermalExpansion

**Comment by mitchej123** [comment]
Try grabbing our fork if you haven't already we've fixed several bugs

**Comment by manskyn** [comment]
> Tente pegar nosso fork, se ainda não o fez, corrigimos vários bugs

What do you mean fork? It's because I'm Brazilian and I don't understand much English.

**Comment by manskyn** [comment]
> Try grabbing our fork if you haven't already we've fixed several bugs

Hello, thank you for trying to help me but my error has been resolved

**Comment by manskyn** [comment]
> Try grabbing our fork if you haven't already we've fixed several bugs

I removed the mods and got it from another mod pack and my Nei is working :)
