### ISSUE TITLE
Crashes while loading 

### ISSUE THREAD

**Issue by StaffiX** [GTNewHorizons/NotEnoughItems#448]
Using
GTNH NEI 2.5.0
CodeChickenLib 1.2.0
CodeChickenCore 1.2.0
Crashes before the game finished loading with this error
[fml-client-1.log](https://github.com/GTNewHorizons/NotEnoughItems/files/13855422/fml-client-1.log)

**Comment by RaidhoSketch** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/13861933/fml-client-latest.log)
Pretty much the same issue. Fixed by downgrading NEI back to 2.4.13.
