### ISSUE TITLE
In-game characters unexpected moving while typing in search bar.

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/NotEnoughItems#459]
pack ver:nightly-353

Repro steps: Searching items in NEI search bar.
Expected: While performing search my character should stay still.
Actual: My in-game character moving corresponding to search bar input.
Video:
https://cdn.discordapp.com/attachments/401118216228831252/1209467862406930502/Jdk-21_2024.02.20_-_19.48.02.01.mp4?ex=65e707b9&is=65d492b9&hm=88def334604727b36fb125f480aae5d5066c21e5143eb1230a038a9dcc4bc24f&

**Comment by BritishCynic** [comment]
Fixed in dev with Nightly 354.
