### ISSUE TITLE
ConcurrentModificationException when clicking on bookmarked item

### ISSUE THREAD

**Issue by ThePixelbrain** [GTNewHorizons/NotEnoughItems#46]
**Mod-Version:** NotEnoughItems-1.7.10-2.0.9-GTNH-universal.jar
**Forge-Version:** 1614
**Modpack:** FTB Infinity Evolved Skyblock 2.0.1 ([Modlist on Curseforge](https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved-skyblock/relations/dependencies))
**Log:** https://pastebin.com/Dq8qvsZD

**Issue Description:**
I rarely have an issue that I can't see the recipe of a bookmarked item. I click on the item, the recipe GUI doesn't open and I get a ConcurrentModificationException in the log. Clicking the item multiple times will eventually show the recipe.
I wasn't able to narrow the problem down to specific items or mods that seem to cause this.
Sometimes this issue doesn't happen at all, sometimes 3/4 of attempts fail and throw a exception.

**Comment by mitchej123** [comment]
This is a race condition in BloodMagic, that is triggered via the concurrent NEI handler initialization.  We fixed it by modifying the BloodMagic source - https://github.com/GTNewHorizons/BloodMagic/pull/10

I'll ponder if there's anything we can do on the NEI side, like perhaps forcefully triggering the BloodOrbCache before concurrent intializating, or adding an option to disable the concurrency.
