### ISSUE TITLE
game crashing on startup

### ISSUE THREAD

**Issue by xedurqs** [GTNewHorizons/NotEnoughItems#462]
after i added nei and code chicken my game started crashing on startup
[fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/14360207/fml-client-latest.log)

**Comment by miozune** [comment]
- It's missing AE2FC.
- GTNH fork of GT5u is not supported for outside of the modpack. https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/edit#gid=382329603
