### ISSUE TITLE
Crash bookmark

### ISSUE THREAD

**Issue by LemonNick** [GTNewHorizons/NotEnoughItems#464]
> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 2/28/24 2:22 PM
> Description: Unexpected error
> 
> java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
> 	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
> 	at codechicken.nei.BookmarkPanel.loadBookmarksIfNeeded(BookmarkPanel.java:1600)
> 	at codechicken.nei.BookmarkPanel.resize(BookmarkPanel.java:1650)
> 	at codechicken.nei.LayoutStyleMinecraft.layout(LayoutStyleMinecraft.java:107)
> 	at codechicken.nei.LayoutManager.layout(LayoutManager.java:346)
> 	at codechicken.nei.LayoutManager.load(LayoutManager.java:622)
> 	at codechicken.nei.guihook.GuiContainerManager.load(GuiContainerManager.java:412)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
> 	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1895)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
> 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
> 	at pro.gravit.utils.launch.LegacyLaunch.launch(Unknown Source)
> 	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(Unknown Source)
> 	at pro.gravit.launcher.client.ClientLauncherEntryPoint.realMain(Unknown Source)
> 	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(Unknown Source)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
> 	at codechicken.nei.BookmarkPanel.loadBookmarksIfNeeded(BookmarkPanel.java:1600)
> 	at codechicken.nei.BookmarkPanel.resize(BookmarkPanel.java:1650)
> 	at codechicken.nei.LayoutStyleMinecraft.layout(LayoutStyleMinecraft.java:107)
> 	at codechicken.nei.LayoutManager.layout(LayoutManager.java:346)
> 	at codechicken.nei.LayoutManager.load(LayoutManager.java:622)
> 	at codechicken.nei.guihook.GuiContainerManager.load(GuiContainerManager.java:412)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
> 	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1895)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [GCEntityClientPlayerMP['valera2crazy'/2136031, l='MpServer', x=-4739.51, y=72.62, z=1581.04]]
> 	Chunk stats: MultiplayerChunkCache: 169, 169
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (1000,100,1000), Chunk: (at 8,6,8 in 62,62; contains blocks 992,0,992 to 1007,255,1007), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
> 	Level time: 3912457990 game time, 2558261315 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> 	Retry entities: 0 total; []
> 	Server brand: thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
> 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
> 	at pro.gravit.utils.launch.LegacyLaunch.launch(Unknown Source)
> 	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(Unknown Source)
> 	at pro.gravit.launcher.client.ClientLauncherEntryPoint.realMain(Unknown Source)
> 	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(Unknown Source)

**Comment by slprime** [comment]
What GTNH version?
What is you PC locale?

fast fix: remove bookmarks.ini
