### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaBro123** [GTNewHorizons/NotEnoughItems#466]
Title, report (with modlist (thank Forge for creating that for you)) below.

Error: https://pastebin.com/sehF6Aw2
Entire log file: [fml-client-latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/14465566/fml-client-latest.log)

**Comment by Caedis** [comment]
What makes you think this is cause of NEI?

**Comment by Caedis** [comment]
Also I dont see a modlist in there.

**Comment by MagmaBro123** [comment]
Ctrl+F exists. Search for NEI

[modlist.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/14466148/modlist.txt)

**Comment by Caedis** [comment]
Looks like some mod's ASM failed to apply because something else already touched it.

**Comment by MagmaBro123** [comment]
Might be NEIIntegration, though I'm unsure why.

**Comment by Caedis** [comment]
Doesnt have ASM.

Try disabling FalseTweaks first to see if that fixes it.

**Comment by miozune** [comment]
You have two NEI jars installed: `NotEnoughItems-1.7.10-1.0.5.120-universal.jar` and `NotEnoughItems-2.5.21-GTNH.jar`

I think we could implement this feature https://github.com/GTNewHorizons/NotEnoughItems/issues/179

**Comment by MagmaBro123** [comment]
Prism being Prism once again... Ugh.
