### ISSUE TITLE
Integrated history widget doesn't show up

### ISSUE THREAD

**Issue by Abalieno** [GTNewHorizons/NotEnoughItems#467]
I've tried since it was added in version 5.21, up to 5.23

I used to have NEI-Utilities working, but since it was merged I removed the separate mod.

No matter the in-game settings, that history bar doesn't show up. Just the standard display as usual.

(separate modpack, using all latest version from the repository, including Angelica, if it matters)

**Comment by slprime** [comment]
Look at the history panel settings, maybe you turned it off

**Comment by Abalieno** [comment]
As I said "no matter the in-game settings".

I fiddled with those options for a while.

**Comment by slprime** [comment]
Weird. In build 369 it work fine

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/841e7cd1-6491-45b9-bb82-4c1dd3cc7c3c)

**Comment by Abalieno** [comment]
I found the reason.

The history panel not shown depends on the item quantity widget set to off.

Please fix :)
I mean, they shouldn't depend on each other. I had it off, so that's why the history panel didn't show up.

**Comment by Caedis** [comment]
Dont seem to have that issue in the latest nightly of the full pack.

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/18713839/2be49d0f-767a-4463-8c3e-b59cc4d6ba16)

What other mods do you have in that pack?

**Comment by Abalieno** [comment]
try move search bar to the center?
