### ISSUE TITLE
Suggestion: Recipe Filters

### ISSUE THREAD

**Issue by Kankrumm** [GTNewHorizons/NotEnoughItems#47]
Possibly add a search bar below the NEI recipe menu which allows you to filter I/O certain items.

(search bar at bottom)
![image](https://user-images.githubusercontent.com/75053123/111668331-07edf900-87ec-11eb-9d59-95557b8118f1.png)
(filtering recipes with maps only)
![image](https://user-images.githubusercontent.com/75053123/111669885-9d3dbd00-87ed-11eb-95cf-5aba5281c83f.png)

While this may not normally yield much use, a modpack with an immense amount of alternative recipes with entirely different items could definitely have some kind of use from this. And also I hate looking at circuit recipes and cycling through the 30 different recipes to find that one recipe that I'll forget 13 times again when crafting it. At least this way you could search for one or two (or more) items in the recipe (possible separated by a comma) which filters out the recipes not containing that specific item/set of items. Also, not sure of its use, but you could also put in terms which makes it ignore recipes with certain ingredients, possibly? Also mod, NBT, tooltip, and pretty much everything that's available on the regular item catalog search bar, except it searches through recipes instead. 

Maybe two extra filters called U: and M:? To represent "used in" and "made", or something along those lines? At this point, you wouldn't even have to click on the item to see what makes it, you could just use these filters, which would be pretty interesting.

Edit: corrected an image

**Comment by slprime** [comment]
This issue need close because it resolved
