### ISSUE TITLE
CC_ClassWriter crash.

### ISSUE THREAD

**Issue by MagmaBro123** [GTNewHorizons/NotEnoughItems#474]
Title.

Linux users cannot use this mod without a "CC_ClassWriter" crash, even with no other mods besides CCC present. (And whatever this CC_ClassWriter file is, please re-add it. I bet this would solve the issue.)

Full log: https://mclo.gs/qo1Y5PN
Error by itself: https://pastebin.com/4E3Yhakq

**Comment by eigenraven** [comment]
You didn't install CodeChickenLib which is a dependency of CodeChickenCore. CCL has this class.

**Comment by MagmaBro123** [comment]
I will also add that whatever this "CC_Class"writer" thing is, you removing it is the main issue.

The original mod )https://github.com/Chicken-Bones/CodeChickenLib/tree/master) works just fine, but is unusable with this fork.

**Comment by eigenraven** [comment]
It is in our CCL 1.2.1 jar, no one ever removed it:
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/1017004/f5eda385-ee53-4180-a1ae-2789d178fd0d)

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/CodeChickenLib/blame/master/src/main/java/codechicken/lib/asm/CC_ClassWriter.java

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/1894689/a29aa733-820c-4793-a134-588f78fc02a5)

**Comment by Natsukiw** [comment]
The original CodeChickenCore Mod has dependencies.info file, but the version built by GTNH does not have this file, so this startup crash problem occurs. The NEI MOD file has dependencies.info, so using NEI can fix this crash problem.

**Comment by MagmaBro123** [comment]
GTNH should add this file then.
