### ISSUE TITLE
Negation does not work in the search within the recipes of a single mechanism

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NotEnoughItems#486]
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/3153076/ab1ffbb3-c735-4dc7-bc2d-271a6d870b6e)

Negation does not work in the search within the recipes of a single mechanism

GTNH: 2.6.0

NEI: NotEnoughItems-2.6.1-GTNH-jei-search.5da05482ef0.jar

**Comment by slprime** [comment]
It work correct. in this recipe exists item what is "no sugar"
