### ISSUE TITLE
NEI Spams chat when it can't render an item such as the "Ceramic Tile" from Botania, can we have an option to disable these chat error logs?

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/NotEnoughItems#490]
NEI Spams chat when it can't render an item such as the "Ceramic Tile" from Botany, can we have an option to disable these chat error logs?
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/11356565/8c008c37-0640-41d1-aefb-97737baee0c9)
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/11356565/b87710bd-8f28-4ef7-9650-e30e05e4ea24)

**Comment by brandyyn** [comment]
I'd also like to mention that it lags my game a lot when the "ceramic tiles" or any item that has an error during rendering is searched by NEI/on screen

**Comment by brandyyn** [comment]
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/11356565/a014f448-02dc-497d-ae6d-44fd47e3dced)

**Comment by OvermindDL1** [comment]
I'm unable to replicate this, in release or dev.  I also tried binnie's mods here and unable to replicate it directly with latest as well both in release and dev.

**Comment by brandyyn** [comment]
> I'm unable to replicate this, in release or dev. I also tried binnie's mods here and unable to replicate it directly with latest as well both in release and dev.

i am mainly asking for an config option to disable the chat spam for when errors like this happen

**Comment by mitchej123** [comment]
The rendering bug should be tracked down and fixed, not the error suppressed.

**Comment by brandyyn** [comment]
> The rendering bug should be tracked down and fixed, not the error suppressed.

Lets say it happens in an ARR mod for a pack you don't care about, AKA my pack with my mods, sure this time it isn't an ARR mod, but right now we haven't been able to track the cause down, so in the mean time, or for next time when it may be an ARR mod causing it, it would be nice to supress specifically the ingame chat warning, it can still exist in the logs, which I look at.

**Comment by mitchej123** [comment]
Ah in game chat I'm fine with. Not fine with suppressing the logs.
