### ISSUE TITLE
How to add handler in my mod

### ISSUE THREAD

**Issue by BlackSauronEx** [GTNewHorizons/NotEnoughItems#494]
I'd like to fix this without editing the CSV file. This is my mod, but I can't figure out if it's possible to add the information I need inside my mod?
I did integration with the old version of NEI, everything I did works fine with your version, but now I want to add support for your version and remove this small flaw in the screenshot. 
(This is a private mod, there is no point in adding it to the general CSV)

![2024-06-17_16-42-21_java](https://github.com/GTNewHorizons/NotEnoughItems/assets/146664554/f1a72f08-8df5-424c-a9aa-601a85aa6452)

**Comment by mitchej123** [comment]
Use IMC.

GoodGenerators, or https://github.com/Roadhog360/Et-Futurum-Requiem/blob/master/src/main/java/ganymedes01/etfuturum/compat/nei/IMCSenderGTNH.java are two examples
