### ISSUE TITLE
Mod Marked "Unsupported" for Servers on Modrinth

### ISSUE THREAD

**Issue by rehashedsalt** [GTNewHorizons/NotEnoughItems#502]
As a result of this, `mrpack`s for servers will fail to download the mod, causing all manner of strife that that entails, such as crashes from dependency errors and degraded functionality.

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/12635110/297a4faf-d9d8-4411-ab29-addf6aca3a6e)

FWIW, this also appears to affect upstream NEI.

**Comment by mitchej123** [comment]
It's now marked as optional
