### ISSUE TITLE
UI changes size when entering Recipe/Usage mode if Satchels is installed

### ISSUE THREAD

**Issue by lawleagle** [GTNewHorizons/NotEnoughItems#503]
I believe the width should be based on the distance to the right of the screen, instead of the distance to the player inventory, that way other mods can modify the player inventory screen without it affecting NEI's width

**Comment by mitchej123** [comment]
There is an API that other mods can use to say they overlap and have nei adjust.   Foresty does this and we made avarita use it, as examples

**Comment by lawleagle** [comment]
well, exactly. the problem is that it DOES adjust. it should not, it should stay in place where we put it in settings. if it shifts around based on what GUI is open, items move around. at least the inventory and recipe/usage screen should always have NEI in the same place
