### ISSUE TITLE
[BUG]The NotEnoughCharacters can't work well as before with recent NEI version

### ISSUE THREAD

**Issue by NealDeal34** [GTNewHorizons/NotEnoughItems#507]
I don't know what happend but the https://github.com/GTNewHorizons/NotEnoughCharacters looks totally not work with the latest version NEI

**Comment by NealDeal34** [comment]
It seems that the last mached available version was 2.6.5(even not [2.6.7](https://github.com/GTNewHorizons/NotEnoughItems/compare/2.6.6-GTNH-pre...2.6.7-GTNH-pre)),help!!!

**Comment by slprime** [comment]
yes, author of [NotEnoughCharacters](https://github.com/GTNewHorizons/NotEnoughCharacters) dont update it yet

**Comment by vfyjxf** [comment]
please use [NeverEnoughCharacters](https://github.com/vfyjxf/NeverEnoughCharacters) ,[NotEnoughCharacters](https://github.com/GTNewHorizons/NotEnoughCharacters) had died
