### ISSUE TITLE
[2.1.0-GTNHA-beta] Current Page Number Persists Between Different Tabs

### ISSUE THREAD

**Issue by MeniMeniMeni** [GTNewHorizons/NotEnoughItems#51]
GTNH and NEI are both 2.1.0. Playing on MP with the beta NEI only being client side.

Page number stays the same when switching between tabs (for example, furnace to wiremill). When exceeding available page numbers, this results in an empty recipe with no way to change the page number, unless you switch back to a tab with at least that many pages.

This does not seam to persist when clicking on a new recipe, but does persist when tabbing back to previously viewed recipes. It will also change back to 1 if you re-click the same recipe.

Attached some pictures of before/after:
![image](https://user-images.githubusercontent.com/14153109/111895147-aa6dce00-89de-11eb-8d8e-6b4270b16e1d.png)
![image](https://user-images.githubusercontent.com/14153109/111895150-b0fc4580-89de-11eb-8769-5ed0e4851437.png)

**Comment by leagris** [comment]
Can also cause an IOOBE:
[crash-2021-03-21_14.52.55-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6177539/crash-2021-03-21_14.52.55-client.txt)

**Comment by MeniMeniMeni** [comment]
Based on the crashlogs from leagris, #63, and mine: https://pastebin.com/N98JRvKQ the IOOBE seem to happen specifically on the shapeless recipe tab.

**Comment by mitchej123** [comment]
Fixed.  Reset page number on tab click.
