### ISSUE TITLE
nei 2.6.23-pre needs a non-existent version of hodgepodge to work?

### ISSUE THREAD

**Issue by danRP408** [GTNewHorizons/NotEnoughItems#513]
mods list:
- CodeChickenCore-1.3.6
- NotEnoughItems-2.6.23-GTNH-pre
[fml-client-latest.log](https://mclo.gs/tuAWItU)
![image](https://github.com/user-attachments/assets/d0b88dc8-0b0b-44d9-a8d0-e4b5a6f0dde3)
https://github.com/GTNewHorizons/Hodgepodge/releases/tag/2.5.43-pre

**Comment by mitchej123** [comment]
It's a pre-release, expect things to break.  It's a known issue that's been brought up in the PR review and will be addressed https://github.com/GTNewHorizons/NotEnoughItems/pull/509
