### ISSUE TITLE
[Bug?] Show recipe key not working when bound to anything but 'R'

### ISSUE THREAD

**Issue by dhasial** [GTNewHorizons/NotEnoughItems#514]
If I rebind the "show recipe" key to anything but R, it just doesn't work, nothing happens. But if it's changed to R it works normally. 

I also checked if I had it bound in the controls, it was only bound to "open backpack" which only works when outside of a menu, and the bug persisted even when this was unbound.

NEI version 2.6.23-GTNH-pre and 2.5.28-GTNH

**Comment by slprime** [comment]
Need more details. I tested in nightly-587 and it work. i tested with N key
