### ISSUE TITLE
Dying leads to missing bookmark pages.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/NotEnoughItems#520]
2.6.24-GTNH-pre
https://clips.twitch.tv/CreativeEmpathicPterodactylLitty-IJNapwnYB6lMAeR4

I just noticed this, was only occurring within a fresh 2.6.1 GTNH instance that has a couple updated mods & Garden of Grind config changes.

You can see in the clip that my pages went from 5/6 to 1/2.

(I'm on this specific version because versions above 2.6.24 atm are causing me to crash with an applecore crash error, no idea why).

**Comment by OlliedeLeeuw** [comment]
We've been having this same issue, on nightly 583 with removed HardcoreDarkness and removed AmazingTrophies, happening to multiple people on our server. (Sometimes the bookmarks even reappear after death)

**Comment by slprime** [comment]
I was able to reproduce it. will fix it.
