### ISSUE TITLE
NEI stuck on Loading Item List

### ISSUE THREAD

**Issue by xSaucychan** [GTNewHorizons/NotEnoughItems#524]
issue: Nei seems to be stuck on loading item list when Immersive Engineering is installed

Mods installed
CoFH Core 3.1.4
Immersive Engineering 0.7.7
NotEnoughItems 2.6.33
CodeChicken Core 1.3.6
Thermal Foundation 1.2.6

Prisim Launcher log: https://mclo.gs/VduczlK
Additional info: removing thermal foundation and cofh core or adding additional mods appear to not cause the issue and is only a problem when Immersive Engineering is installed. The Last 2 screenshots is an instance of 291 mods both before and after adding immersive engineering)
![2024-09-01_00 36 56](https://github.com/user-attachments/assets/75867fbb-ce75-40de-b9a4-a3ba208aa7f4)
![2024-09-01_00 35 58](https://github.com/user-attachments/assets/4ea3c6db-94df-45c7-b662-a53aec22e427)
![2024-09-01_02 00 45](https://github.com/user-attachments/assets/f3450c75-a11d-4b9d-a93c-aac689b2cb65)
![2024-09-01_02 04 55](https://github.com/user-attachments/assets/4ed0140e-cc61-49e7-a920-025b8b3530ed)

**Comment by slprime** [comment]
need more details. everything works fine for me with these mods

**Comment by xSaucychan** [comment]
I'll try again and update the issue with a fresh install of all the listed mods in if the problem continues. Would additional log files possibly provide sufficient info on what the cause is

**Comment by slprime** [comment]
was able to reproduce the problem
