### ISSUE TITLE
Search for ProjectE transmutation tablet does not work, NEI In versions later than 2.6.8-GTNH

### ISSUE THREAD

**Issue by NyanjiroJPN** [GTNewHorizons/NotEnoughItems#526]
All mod versions are the same except NEI
However, if the NEI version is upgraded from 2.6.8, the search will not work.
Because the NEI was changed specifically from versions later than 2.6.8?
Initializing both NEI and projectE config did not change it
Can it be cured by changing the NEI settings in the game?

**Comment by slprime** [comment]
yes, projectE uses ISearchProvider and generate the search itself instead of using ItemList.getItemListFilter. The problem can only be solved by correcting the projectE.

**Comment by NyanjiroJPN** [comment]
omg...
Are you saying that future versions of NEI will not cure this?

**Comment by sousuke0422** [comment]
Some add-ons break, but FMProjectE, updated yesterday, fixes this problem.

**Comment by NyanjiroJPN** [comment]
Thanks, I'll give it a try!
