### ISSUE TITLE
[Suggestion] GUI blacklist option

### ISSUE THREAD

**Issue by xJon** [GTNewHorizons/NotEnoughItems#529]
(From https://github.com/GTNewHorizons/NotEnoughItems/issues/369#issuecomment-2323116823)
> Implementing a `hiddenitems.cfg` is great, but would you also consider an option for hiding items in-game, similarly to JEI? It also helps visually grasping what you are hiding.
I believe the current method (in contrast) requires manually inserting the relevant item IDs into the config file.

**Comment by slprime** [comment]
Use Presets to hide items. https://discord.com/channels/181078474394566657/295669878222880769/1266833830267060275

`hiddenitems.cfg` need for modpack creators

**Comment by xJon** [comment]
@slprime Thank you for letting me know about the new Presets system, it works great and has more features than expected.
