### ISSUE TITLE
[2.1.0-GTNHA-beta] NumberFormatException Crash From Null Value

### ISSUE THREAD

**Issue by MeniMeniMeni** [GTNewHorizons/NotEnoughItems#53]
Noticed my bookmarks had mysteriously disappeared and attempted to re-enable them. Got a NumberFormatException crash from a null value after pressing the button to enable bookmarks.

Crash log: https://pastebin.com/Jugi243t

Null value for bookmarksEnabled.value persists through a client reboot. Opening client.cfg shows the value as "false".
![notepad++_VQY7CobN1h](https://user-images.githubusercontent.com/14153109/111899752-64bffe00-89fc-11eb-90d7-cbe6fb07ce5d.png)
However manually changing the value in the file to "true" seams to temporarily fix the problem and re-enables bookmarks until I try to click the button again. The toggle button seams to always read the value as null regardless of the .cfg.

**Comment by leagris** [comment]
Version: NotEnoughItems-1.7.10-2.1.0-GTNH-beta-universal

Same here:  `java.lang.NumberFormatException: bookmarksEnabled.value=null`
[crash-2021-03-21_12.09.43-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6177262/crash-2021-03-21_12.09.43-client.txt)
