### ISSUE TITLE
[2.1.0-GTNHA-beta] Bookmark icons scales badly

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/NotEnoughItems#55]
With GUI Scale Auto and 1920×1080 screen, the toggle bookmarks icon renders very badly compared to the options icon:

![image](https://user-images.githubusercontent.com/1111474/111903193-50522480-8a41-11eb-9913-f8578c72271a.png)

Instead I propose you use these not up-scaled:

16×16 pixels icons:
![image](https://user-images.githubusercontent.com/1111474/111903693-d0798980-8a43-11eb-9a09-97da760eef3a.png)

Compared to the current borked pre-scaling, these would scale as fairly as the wrench option icon:

![image](https://user-images.githubusercontent.com/1111474/111904154-9c06cd00-8a45-11eb-8ad7-bfc4fd78b553.png)

**Comment by mitchej123** [comment]
If this persists after the next beta please let me know, or swap out the assets on nei_tabbed_sprites.png
