### ISSUE TITLE
[Suggestion] Allow pack devs to customize collapsible groups (and make the spawn egg one include modded spawn eggs)

### ISSUE THREAD

**Issue by vizthex123** [GTNewHorizons/NotEnoughItems#552]
Other than adding config options, I also thought of a few extra groups that could be added:

- Crated items from Forestry. Could hide them instead if it doesn't impact the recipe viewing.
- Bees, Butterflies, and Caterpillars from Forestry (and Magic Bees)
- Basically all of the repetitive items from Forestry
- Logs
- Planks
- 

Extra item hiding:
- All facades (from Buildcraft and AE2) & microblocks (from forge and extra utilities)
- Lit furnace
- Bedrock
- Thaumcraft's technical eldritch blocks (the "nothing" and portal frame)
 
I also noticed that filtering to `@buildcraft` only renders a handful of items even if you've got all the modules installed (in my case, I have the full non-modular mod).

**Comment by chochem** [comment]
you can already do so. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/NEI/collapsibleitems.cfg for an example.

**Comment by chochem** [comment]
while hiding is done like this https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/NEI/hiddenitems.cfg

**Comment by vizthex123** [comment]
> you can already do so. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/NEI/collapsibleitems.cfg for an example.

hm, that's not in the config folder by default.



> while hiding is done like this https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/NEI/hiddenitems.cfg

yeah, i found that one. Would just be nice if more stuff was hidden by default lol.

**Comment by chochem** [comment]
was added in August. I guess you just need to update.

**Comment by vizthex123** [comment]
probably, yeah. Sorry for the false report lol.

**Comment by wlhlm** [comment]
> probably, yeah. Sorry for the false report lol.

No need to apologize. Our documentation is not the best.
