### ISSUE TITLE
The rendering bug of the Zoom Position feature in NotEnoughItems.

### ISSUE THREAD

**Issue by Omgise** [GTNewHorizons/NotEnoughItems#556]
### Mod Version

NotEnoughItems-2.6.44-GTNH.jar

### Bug Report

Generating eggs and potions will cause the Zoom Position feature to malfunction.

https://github.com/user-attachments/assets/77dc790d-dcd0-460a-bca0-5746f47751ca

### Java Version

Java 8

### Mod List or GTNH Pack Version

There's no conflict.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by Alexdoru** [comment]
it shouldn't even be rendering the item zoom when the NEI item panel isn't visible imo

**Comment by slprime** [comment]
There are more problems here than you think
![image](https://github.com/user-attachments/assets/76d9f37e-095d-424c-b2a5-267c770e68a7)

**Comment by slprime** [comment]
in nightly 736 its works fine. check version of CodeChickenCore (1.3.10 for me)
![image](https://github.com/user-attachments/assets/ac6c8e40-3420-4001-be34-5f10aaff5607)

**Comment by Omgise** [comment]
After upgrading CodeChickenCore to version 1.3.10, the game crashed.
[crash-2024-11-17_18.48.01-client.txt](https://github.com/user-attachments/files/17789948/crash-2024-11-17_18.48.01-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/17789949/fml-client-latest.log)

**Comment by Omgise** [comment]
I also tried the 2.6.45 version of NotEnoughItems before, and it would crash as well.

**Comment by Omgise** [comment]
The `NotEnoughItems-2.6.45-GTNH-git.1+d70931a7e0-dirty` version also crashes

**Comment by slprime** [comment]
@Omgise try disabled BetterTooltipBox mod

**Comment by Omgise** [comment]
Yes, disabling the BetterTooltipBox mod will prevent the game from crashing.

**Comment by Omgise** [comment]
@slprime Is it possible to make BetterTooltipBox mod compatible in the future?
This is its source code: https://github.com/xiaoxing2005/BetterTooltipBox
