### ISSUE TITLE
Item subsets grayed out and cannot be turned on

### ISSUE THREAD

**Issue by PreDawnHydra** [GTNewHorizons/NotEnoughItems#557]
### Mod Version

2.6.46

### Bug Report

I swapped out the old Not Enough Items mod for the GTNH version and it works great however a few of the mods have subsets that I cannot turn on for some reason, at first I thought the mods were not being loaded since a bunch of items were missing, then I realized the recipes are still in game and craftable but for whatever reason the subsets seen in the picture refuse to be enabled when I left click them.
Because the recipes still show when I press "U" on the HV transformer for the tesla coil, or wood for the ship's helm I am assuming there must be some config option I am overlooking? 
These mods worked fine in the default NEI for 1.7.10 I am unsure of a good way to track down this issue further, let me know if you need any more info!

Ships helm from Archimedes ships is registered and displayed as a recipe if I use the "U" button on wood
![2024-11-25_05 56 08](https://github.com/user-attachments/assets/a894eb95-d87f-4937-a24e-e131a2fb4b6f)

Here the subset is shown grayed out
![2024-11-25_05 56 14](https://github.com/user-attachments/assets/f5d50122-6159-4b07-8904-35fb4c4a99b6)

Similarly with the tesla coil, I am aware I have the backpack filter in the search on in this picture I tried removing it still the same issue:
![2024-11-25_05 52 11](https://github.com/user-attachments/assets/d223f480-c698-47b6-9341-54c292c71551)
![2024-11-25_05 52 17](https://github.com/user-attachments/assets/cff0ce46-149c-45d2-a50b-607a7a8648b7)
![2024-11-24_23 40 16](https://github.com/user-attachments/assets/188d10c0-e9bb-4c08-88a1-2d36dcf01dfb)

### Java Version

Java 8

### Mod List or GTNH Pack Version

(See pictures for mods likely causing issues)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by slprime** [comment]
duplicate: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17600
