### ISSUE TITLE
[2.1.0-GTNHA-beta] Unlit itemblocks tab icons

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/NotEnoughItems#58]
![image](https://user-images.githubusercontent.com/1111474/111907222-abd9dd80-8a54-11eb-9b93-24ca594efe05.png)

![image](https://user-images.githubusercontent.com/1111474/111905092-4d0f6680-8a4a-11eb-87c8-cee254daa915.png)

**Comment by Zenthae** [comment]
same for me, unlit, and not border when using a ressource pack

**Comment by mitchej123** [comment]
Haven't tracked this down, it's intermittent and not reproducible on demand.
