### ISSUE TITLE
[2.1.0-GTNHA-beta] Tabs and paging shall reuse creative GUI assets and layout

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/NotEnoughItems#59]
If tabs and paging were re-using the creative inventory assets and layout:

- It would unify the rendering and layout.
- Avoid loading more resources.
- Allow a proper rendering with existing resources-packs without having to update it.

Default textures rendered creative inventory tabs;

![image](https://user-images.githubusercontent.com/1111474/111905382-a88e2400-8a4b-11eb-820f-20f1ff30600d.png)

Resources-pack rendered creative inventory tabs:

![image](https://user-images.githubusercontent.com/1111474/111905348-7977b280-8a4b-11eb-9933-39918e6a47a7.png)

**Comment by HeroOfOlympus** [comment]
Great idea, I'm using right now faithful resource pack and that's how it looks like. 
![image](https://user-images.githubusercontent.com/76167918/111906096-3e777e00-8a4f-11eb-9717-07c06b314c3e.png)

**Comment by mitchej123** [comment]
Fixed. There's now an option to use creative or JEI style tabs.  The JEI style tabs also use a new resource so they won't conflict with existing resource packs that don't support them.
