### ISSUE TITLE
[2.1.0-GTNHA-beta] some tabs have no or weird icons

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NotEnoughItems#60]
![image](https://user-images.githubusercontent.com/12850933/111907687-bd23e980-8a56-11eb-8a09-aaf94cc2db02.png)
this seem to be a valid icon tho, because this is what is displayed when i hover it:
![image](https://user-images.githubusercontent.com/12850933/111908018-e8f39f00-8a57-11eb-90c1-e679fb522d20.png)

![image](https://user-images.githubusercontent.com/12850933/111907711-d6c53100-8a56-11eb-99a1-903aa5f3a4c2.png)
when the icon is hovered:
![image](https://user-images.githubusercontent.com/12850933/111907778-1be96300-8a57-11eb-8aa3-9ffffa080f4e.png)

![image](https://user-images.githubusercontent.com/12850933/111907753-05dba280-8a57-11eb-9ba8-732e11c127ec.png)
when the icon is hovered:
![image](https://user-images.githubusercontent.com/12850933/111907884-6a96fd00-8a57-11eb-81ee-4185ddaec173.png)
![image](https://user-images.githubusercontent.com/12850933/111908062-09bbf480-8a58-11eb-9081-32e553be14ef.png)
when the icon is hovered:
![image](https://user-images.githubusercontent.com/12850933/111908082-21937880-8a58-11eb-8bfd-820a5519d2a1.png)

That's all i found, will update the issue if i find new ones

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/111908268-d9c12100-8a58-11eb-9245-a067904615aa.png)
when i hover it:
![image](https://user-images.githubusercontent.com/12850933/111908281-ea719700-8a58-11eb-8472-2d438efe4dd7.png)

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/111908350-2f95c900-8a59-11eb-9203-05143cc0c8f8.png)
![image](https://user-images.githubusercontent.com/12850933/111908363-3f151200-8a59-11eb-8590-a9a84bab810f.png)

![image](https://user-images.githubusercontent.com/12850933/111908373-4b996a80-8a59-11eb-9916-f2eeb9543a0c.png)
![image](https://user-images.githubusercontent.com/12850933/111908382-59e78680-8a59-11eb-8196-08f6fc08221b.png)

**Comment by mitchej123** [comment]
Go to tools, data dumps, and dump out the handlers.csv

![image](https://user-images.githubusercontent.com/1894689/111912992-5c31ec80-8a29-11eb-96c6-3757d9dcd940.png)

Much easier than images, since I'll need the strings (and a suggested itemstack) to fix.  The default ones I can fix, but please provide the aroma one since I'm assuming it's from aromabackup and I don't have that in my pack

**Comment by boubou19** [comment]
[handlers.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6177901/handlers.txt) (had to change the extension to get it sent here)

I have no idea how aroma came into my pack, so i assume it's provided in the 2.1.0.0 technic launcher pack. Anyways, it should be included in the dump.

**Comment by mitchej123** [comment]
Most of these should be fixed, if not make a new issue with a new handlers.csv dump, and a few images of what's missing.
