### ISSUE TITLE
Crash when clicking specific tab 

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/NotEnoughItems#63]
Just like it says on the tin.

Crashlog: https://pastebin.com/3XFUwfzg

**Comment by mitchej123** [comment]
Which tab?

**Comment by MeniMeniMeni** [comment]
Possibly related to the IOOB obtainable from: #51

**Comment by tyrael93** [comment]
> Which tab?

GT6 tool+handle tab, a huge, hulking amount of shapeless recipes.

**Comment by Dr-Turtle** [comment]
I had a similar crash - Occured when clicking on the shaped crafting for dark steel ingots (non-replicable)
https://pastebin.com/Bu3Q20sA

**Comment by Dream-Master** [comment]
I got a crash too when switching between assembler and crafting table recipe (checking the new bed recipe)
[crash-2021-03-22_19.24.48-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6184525/crash-2021-03-22_19.24.48-client.txt)

**Comment by mitchej123** [comment]
Fixed
