### ISSUE TITLE
Can only use the right three spots in item responder chip filter

### ISSUE THREAD

**Issue by Houndie** [GTNewHorizons/NotEnoughItems#64]
#### Which modpack version are you using?
2.0.8.8

#
#### If in multiplayer; On which server does this happen? 
N/A

#
#### What did you try to do, and what did you expect to happen?
Pick up an item and be able to place it in the filter for the ProjectRed Item Responder Chip.

#
#### What happened instead? (Attach screenshots if needed)
Item ejects onto ground

#
#### What do you suggest instead/what changes do you propose?
Let me place the item in the Item Responder Chip Filter.

It looks like because the "filter" dialog is only a pop up on top of the regular dialog, only the spots on the pop up dialog that overlay the bottom dialog work.  Any spots on the pop up dialog that don't overlay the bottom dialog functionally don't exist, which is why items drop on the ground when trying to place an item in that spot.

I'm going to try and see if this reproduces outside of GT:NH next, as well as see if there's a more recent version of projectred out there that doesn't have this problem.

**Comment by mitchej123** [comment]
I've moved the bookmark right border to the left a bit, it looks like this might still stick out too far; please test with the latest and report back.  There's also an option to toggle the bookmark panel that should help with this.
