### ISSUE TITLE
Feature Request: Option to disable scrolling item transfer

### ISSUE THREAD

**Issue by Ariistuujj** [GTNewHorizons/NotEnoughItems#66]
This feature of NEI can conflict with other mods (mouse tweaks, item scroller) and was fixed by adding the option to disable it in newer versions.
https://github.com/TheCBProject/NotEnoughItems/commit/7943831c2a8898fd6805d39fba57397742ba37f9
Could this please be added to this fork of NEI? Much appreciated.

**Comment by mitchej123** [comment]
Will look into it

**Comment by mitchej123** [comment]
Done
