### ISSUE TITLE
EBF recipe info extends past gui window

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/NotEnoughItems#71]
![image](https://user-images.githubusercontent.com/16054364/112549868-b4475680-8d7b-11eb-850b-8ccfa4baac66.png)

**Comment by Florexiz** [comment]
Same applies for cleanroom/low gravity requirements
![image](https://user-images.githubusercontent.com/29033773/112594659-5289f980-8e1a-11eb-91e8-66613ec451fc.png)

**Comment by mitchej123** [comment]
Fixed in beta5
