### ISSUE TITLE
Wrong handler images

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#72]
Using beta3. [handlers.zip](https://github.com/GTNewHorizons/NotEnoughItems/files/6208987/handlers.zip)

This appears to be the GT++ basic rocket engine. It should be a combustion generator/engine. I don't think there's anything you can do about the text+arrows, right?
![image](https://user-images.githubusercontent.com/8517039/112568667-34d87800-8db9-11eb-893e-9d7f733fe7c9.png)

Semifluid boiler fuels. Should probably be a boiler of some kind instead. I mean, you _can_ use it in a boiler, right? It says so after all. It appears to be the GT++ semifluid generator.
![image](https://user-images.githubusercontent.com/8517039/112568897-96004b80-8db9-11eb-9acc-411d10198d21.png)

Gas turbine fuel is using the GT++ ULV instead of the LV one.
![image](https://user-images.githubusercontent.com/8517039/112569120-f8594c00-8db9-11eb-85f6-61432d1ea8ce.png)

Rocket engine fuel shows a rocket instead of a GT++ rocket fuel gen. Though if you want to make another handler for GC+addons to show what rocket fuels go with what rocket someone _might_ use that? I wouldn't bother though.
![image](https://user-images.githubusercontent.com/8517039/112569205-1d4dbf00-8dba-11eb-82ae-2aa0e5d1f683.png)

Steam and SH steam don't show a use in the steam turbine or multi versions. I'm guessing there's no handler because there's only 1 type of fuel for these?

**Comment by Prometheus0000** [comment]
I also think it would be nice if the byproduct page had a nicer/clearer picture if someone could suggest one.
![image](https://user-images.githubusercontent.com/8517039/112570234-0dcf7580-8dbc-11eb-8fcb-4fe13bac5bd8.png)

**Comment by mitchej123** [comment]
If you'd like to update any of the tab icons please look at GuiRecipeTab.java .  Provide the appropriate handler class, and new item (result of `/mt hand`).  

As for the spacing, check beta4; I've adjusted the display a bit.

**Comment by mitchej123** [comment]
> I also think it would be nice if the byproduct page had a nicer/clearer picture if someone could suggest one.
> ![image](https://user-images.githubusercontent.com/8517039/112570234-0dcf7580-8dbc-11eb-8fcb-4fe13bac5bd8.png)

Almost all of the byproducts are listed as dusts; hence the dust icon.  I'm fine if anyone has a better suggestion
