### ISSUE TITLE
Stretched GUI does not show additional recipes on the same page

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#75]
![image](https://user-images.githubusercontent.com/8517039/112735172-c7475b80-8f20-11eb-8be0-be689dbc1d68.png)
![image](https://user-images.githubusercontent.com/8517039/112735180-cdd5d300-8f20-11eb-8479-f9ea281c9bdc.png)
Uses of planks. These should be on the same page, yes?
For another example, there's raw carbon fibre. It has 4 versions of how to make it, but only 1 is shown on the page.
![image](https://user-images.githubusercontent.com/8517039/112735222-fbbb1780-8f20-11eb-836c-597f08149e01.png)

beta5

**Comment by mitchej123** [comment]
It's all a giant hack since the recipe handlers don't indicate their height.  I did some shenanigans with some assumptions.  Any others will need to be special cases in a config.  Working out what that might look like.
