### ISSUE TITLE
Specific handler text not centered

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#76]
![image](https://user-images.githubusercontent.com/8517039/112735295-594f6400-8f21-11eb-9f72-829e3a75315d.png)

beta5

**Comment by Prometheus0000** [comment]
```java
	@Override
	public String getRecipeName() {
		return "          " + StatCollector.translateToLocal("tile.bloodAltar.name");
	}        
```
Y U do this, BM?

Is there a way to shift this for people not using our custom build of BM? It's not a huge issue, so we could just give up on it?

**Comment by Dream-Master** [comment]
This name is custom. Not sure if we changed it in BM or in a script.

**Comment by Prometheus0000** [comment]
That's literally the code I posted.

**Comment by Prometheus0000** [comment]
I see what you mean now, but the code is adding a giant space, regardless of the name.

**Comment by Prometheus0000** [comment]
```
// --- Nei Rename ---



// --- Blood Altar
<AWWayofTime:Altar>.displayName = "Altar of GregoriusT's Blood";
```
From the script file

**Comment by glowredman** [comment]
Calling `.trim()` [here](https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/codechicken/nei/recipe/GuiRecipe.java#L387) would solve this and all issues like this.

**Comment by Prometheus0000** [comment]
This indeed fixes it, and the chem plant one.
