### ISSUE TITLE
Stretched GUI and the DCT do not get along

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#77]
![image](https://user-images.githubusercontent.com/8517039/112735374-d7136f80-8f21-11eb-9d1a-9cc75973901b.png)

beta5

**Comment by mitchej123** [comment]
Haha. That's hilarious

**Comment by z3r0b0t** [comment]
Here's some more for you : 
![image](https://user-images.githubusercontent.com/36605286/114332267-e1359080-9b13-11eb-8b70-1fe753b23689.png)
![image](https://user-images.githubusercontent.com/36605286/114332269-e4308100-9b13-11eb-959e-942d14e5e58d.png)

Resolution for both images : 3440x1440
UI Scale for first image : Large
UI Scale for 2nd image : Small

**Comment by mitchej123** [comment]
The GUI grows with the screen height, to a maximum of 370px currently.  I don't have it shrink when there isn't enough recipes because the accordioning  would be super annoying, and it'd be challenging to keep the top in the same place with variable height (since it's centered on the screen).

**Comment by Prometheus0000** [comment]
Height 164 gets you two
![image](https://user-images.githubusercontent.com/8517039/118363104-c6b26500-b560-11eb-953b-d399f1cc506e.png)
You can see the discoloration from the bottom one on the upper one there a little
![image](https://user-images.githubusercontent.com/8517039/118363111-cdd97300-b560-11eb-9ce2-ced8818e1304.png)
Additionally, you can see NEI items still overlap part of the extended area, you should adjust that so it stays out of the whole extended area.

Also, you can't mousewheel scroll to see other recipes while the cursor is in the extended area on the right, which is a separate bug I guess. See https://github.com/GTNewHorizons/NotEnoughItems/issues/127

I think it's worth adjusting this way, what do you think? Also, 170 shows only 1, so there's little leeway to have it look nice at the bottom there.
