### ISSUE TITLE
Stretched GUI slightly off for two things

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#79]
The grey are in the second line is a little off
![image](https://user-images.githubusercontent.com/8517039/112735469-a6800580-8f22-11eb-8c4f-b7c2c0893c90.png)
![image](https://user-images.githubusercontent.com/8517039/112735476-af70d700-8f22-11eb-9ca8-005227c903b0.png)
Normal
![image](https://user-images.githubusercontent.com/8517039/112735483-ba2b6c00-8f22-11eb-9bf6-3cd9635cd91c.png)

beta5

**Comment by mitchej123** [comment]
Mod authors with negative y offsets. 😡
