### ISSUE TITLE
Crash (with CustomNPC)

### ISSUE THREAD

**Issue by Vatarus** [GTNewHorizons/NotEnoughItems#8]
Minecraft crashes when you open the CustomNPC Inventory tab.
[crash-2020-01-22_17.11.58-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/4095758/crash-2020-01-22_17.11.58-client.txt)

**Comment by mitchej123** [comment]
Try with beta3.

**Comment by Vatarus** [comment]
beta 3 works fine!
