### ISSUE TITLE
Handler for the mutagen producer from gendustry does not have a correctly localized name

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#80]
![image](https://user-images.githubusercontent.com/8517039/112740964-4d7a9680-8f4f-11eb-84c5-8350f6824abe.png)

**Comment by mitchej123** [comment]
Not sure if this is NEI's fault... but will look more into it

**Comment by mitchej123** [comment]
Bug in gendustry.  It references the translation key `tile.gendustry.mutagen.producer.name` but the key in the file is `tile.gendustry.mutagen_producer.name`

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/gendustry/commits/mc1710/src/net/bdew/gendustry/machines/mproducer/GuiMutagenProducer.scala

Are we using a build that has this? It looks correct in code and the lang file?

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/gendustry/blob/mc1710/resources/assets/gendustry/lang/en_US.lang#L3
![image](https://user-images.githubusercontent.com/1894689/114294645-e089f500-9a54-11eb-813f-a8c49fe34ab5.png)

https://github.com/GTNewHorizons/gendustry/blob/mc1710/src/net/bdew/gendustry/nei/MutagenProducerHandler.scala#L67
![image](https://user-images.githubusercontent.com/1894689/114294655-e7b10300-9a54-11eb-8276-974c9d4bb216.png)

**Comment by Prometheus0000** [comment]
Made a PR to fix.

**Comment by GTNH-Afx237v7** [comment]
Still exists in 2.1.1 (grabbed from Jenkins earlier today)

**Comment by Prometheus0000** [comment]
It was fixed in _gendustry_.

**Comment by GTNH-Afx237v7** [comment]
:D
