### ISSUE TITLE
More handlers with incorrect images

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#81]
![image](https://user-images.githubusercontent.com/8517039/112740987-89156080-8f4f-11eb-8dce-39dfc4a9a090.png)
![image](https://user-images.githubusercontent.com/8517039/112740992-93375f00-8f4f-11eb-926d-ad438c238b3c.png)
Both should be blood orbs

![image](https://user-images.githubusercontent.com/8517039/112741004-b06c2d80-8f4f-11eb-9e1a-6a1ff7303080.png)
Should probably be a saw given it's for microblocks

**Comment by mitchej123** [comment]
@Prometheus0000 If you update the gsheet, I'll pull these and any other changes into the next release

**Comment by Prometheus0000** [comment]
Edited sheet
