### ISSUE TITLE
Cutting Edge Display Issue

### ISSUE THREAD

**Issue by accessdenied0** [GTNewHorizons/NotEnoughItems#82]
I'm not sure this issue is in any form your forks fault, or if it get fixed, but I recently started playing 1.7.10 again and I like to use [CuttingEdge](https://www.curseforge.com/minecraft/mc-mods/cutting-edge).

Now this Mod is sadly not longer in development, so it probably can't or won't be fixed from the Mod-Author.
But the issue is simply that because it errors at displaying, all other recipes won't displayed as well.

Means that no matter which recipe I want to look up the fork won't display anything. Minecraft doesn't crashes, but NEI without recipes function is kinda useless.

I hope you maybe can fix this [issue](https://pastebin.com/EbwyxmTc)...
[Log.](https://puu.sh/Hte5Q/301b019405.log)

**Comment by mitchej123** [comment]
Looks to be the same issue as https://github.com/GTNewHorizons/NotEnoughItems/issues/84

Try the latest version I linked there and report back if you still have the issue.

**Comment by ORANG4** [comment]
Just tested Cutting Edge with [2.1.0 beta8](http://jenkins.usrv.eu:8080/job/NEI/40/artifact/build/libs/NotEnoughItems-1.7.10-2.1.0-GTNH-beta8-universal.jar). All recipes now working
