### ISSUE TITLE
[Feature Request] Can you port jee to gtnh when you rework the overlay buttons?

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/NotEnoughItems#83]
1.12, jee can help you make the encoded pattern very easy.

can you port jee to gtnh by the way?

jee:https://www.curseforge.com/minecraft/mc-mods/just-enough-energistics-jee

**Comment by GTNH-Afx237v7** [comment]
There is already a pattern encoder from AE2 stuff that does the exact same thing

**Comment by iouter** [comment]
> There is already a pattern encoder from AE2 stuff that does the exact same thing

Is it processing patterns？

**Comment by GTNH-Afx237v7** [comment]
Crafting patterns. Also AE2 allows you to drag&click items from NEI into the pattern terminal.

**Comment by iouter** [comment]
jee supports processing patterns. and drag&click only supports 1 stack items to the encoded pattern. sometimes, it's not convenient.

maybe we can use the box in the lower right corner to specify the number of drag&click items.

**Comment by GTNH-Afx237v7** [comment]
Well it’s not up to me to decide and/or do the work, as @mitchej123 is out NEI/JEI expert...

**Comment by iouter** [comment]
yep, just a suggestion.
