### ISSUE TITLE
Factorization slag furnace crash

### ISSUE THREAD

**Issue by ORANG4** [GTNewHorizons/NotEnoughItems#84]
### Crash when viewing any slag furnace recipe from factorization mod.

**NEI version:** 1.7.10-2.0.9
**[Factorization](https://www.curseforge.com/minecraft/mc-mods/factorization-unofficial) version:** 1.7.10-0.8.108
CodeChickenCore version: 1.7.10-1.0.7.47
CodeChickenLib version: 1.7.10-1.1.3.138

[Crash](https://pastebin.com/bdcycjTY)
[Full log](https://pastebin.com/yi8X85Jn)

**Comment by Glease** [comment]
Do we even have this mod in the pack? 

Anyway it looks like that factorization won't work with our fork of NEI any more. Not sure if mitch would want to somehow make it compatible. It'd be quite a bit of work. You'd probably have to stick to the old slower NEI.

**Comment by mitchej123** [comment]
@Glease It's not in the pack, but this repo is linked from curseforge.  My goal is to make it as compatible as possible when possible.

**Comment by Glease** [comment]
So apparently this mod want [this field](https://github.com/GTNewHorizons/NotEnoughItems/blob/7cfa4ae4ca916007dc216ebde1b980f736c489c3/src/codechicken/nei/recipe/FurnaceRecipeHandler.java#L62) back, and the class name of the list content has to be `FurnaceRecipeHandler.FuelPair`.

**Comment by mitchej123** [comment]
Yah... I already moved the FuelPair class back, wasn't expecting anyone to be accessing afuels directly (sigh, too many public things).  Need to see if I can move it back and have the TemplateHandler properly use it.

**Comment by ORANG4** [comment]
Guys, thanks a lot for your hard work on such an old version of mc. I really wasn't expecting this search speed in 1.7.10

**Comment by mitchej123** [comment]
@ORANG4 Try this version and see if it fixes your crash - http://jenkins.usrv.eu:8080/job/NEI/39/artifact/build/libs/NotEnoughItems-1.7.10-2.1.0-GTNH-beta7-universal.jar

**Comment by mitchej123** [comment]
(It also has the beta JEI inspired tab features, so it might crash for other reasons)

**Comment by ORANG4** [comment]
> @ORANG4 Try this version and see if it fixes your crash - http://jenkins.usrv.eu:8080/job/NEI/39/artifact/build/libs/NotEnoughItems-1.7.10-2.1.0-GTNH-beta7-universal.jar

Nope, it [crashed](https://pastebin.com/a6tf1WU8) again 😞

**Comment by mitchej123** [comment]
bah, wrong class

**Comment by mitchej123** [comment]
@ORANG4 Ok this version _should_ work.  Beta8 http://jenkins.usrv.eu:8080/job/NEI/40/artifact/build/libs/NotEnoughItems-1.7.10-2.1.0-GTNH-beta8-universal.jar

**Comment by ORANG4** [comment]
> @ORANG4 Ok this version _should_ work. Beta8 http://jenkins.usrv.eu:8080/job/NEI/40/artifact/build/libs/NotEnoughItems-1.7.10-2.1.0-GTNH-beta8-universal.jar

Works perfectly, thanks!
