### ISSUE TITLE
crash when viewing bluepower alloy furnace recipes

### ISSUE THREAD

**Issue by wasakoki** [GTNewHorizons/NotEnoughItems#85]
[crash-2021-03-30_00.08.21-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/6226337/crash-2021-03-30_00.08.21-client.txt)

not sure if mods not included in GTNH are supported or not but i figured it can't hurt to submit an issue anyway. I tested it with just GTNH NEI and bluepower + dependents installed only. i also tested it in chickbones NEI and no crash occurs when viewing recipe.

to replicate: attempt view the crafting recipe from any of the alloy ingots from bluepower.

**Comment by mitchej123** [comment]
Same issue as https://github.com/GTNewHorizons/NotEnoughItems/issues/84 fixed in latest beta (8+).

**Comment by wasakoki** [comment]
sorry for the duplicate, i just searched "bluepower" and got no results so i figured it was unique

**Comment by mitchej123** [comment]
> sorry for the duplicate, i just searched "bluepower" and got no results so i figured it was unique

no problem.  It was only obvious it was a duplicate by the crashlog
