### ISSUE TITLE
[2.1.0-GTNHA-beta 9] Fluid Info for Tinkers Doesn't Scale Properly

### ISSUE THREAD

**Issue by MeniMeniMeni** [GTNewHorizons/NotEnoughItems#86]
NEI: 2.1.0-GTNHA-beta 9 and beta 5.
GTNH: 2.0.9
Fluid info that appears when hovering recipes for tinkers alloying doesn't appear in the correct positions.

![image](https://user-images.githubusercontent.com/14153109/113223277-6d130700-924e-11eb-8f13-7a6010f4bc82.png)
![image](https://user-images.githubusercontent.com/14153109/113223349-9764c480-924e-11eb-9f81-6e8ccbd04b6c.png)

**Comment by mitchej123** [comment]
This is also an issue with fluids and forestry

**Comment by mitchej123** [comment]
fixed for forestry & ticon in beta 11
