### ISSUE TITLE
[2.1.0-GTNHA-beta 9] Neutronium compressor weird shape

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/NotEnoughItems#90]
Neutronium compressor leaves empty space in right tab
![image](https://user-images.githubusercontent.com/29033773/114218767-84e73b00-9972-11eb-8d1a-d245ad57f0ea.png)
Probably leftovers from this?
![image](https://user-images.githubusercontent.com/29033773/114218814-94ff1a80-9972-11eb-918f-50e9bb04fe98.png)

**Comment by mitchej123** [comment]
please hover over the tab and hold shift, it'll give the handler information

**Comment by mitchej123** [comment]
Fixed
