### ISSUE TITLE
[2.1.0-GTNH-beta12] Increasing handlerWidth does not shift item panel for all rows

### ISSUE THREAD

**Issue by facetorched** [GTNewHorizons/NotEnoughItems#91]
Adding handlers for terrafirmacraftplus anvil which has a wide UI. I increased the handlerWidth to 208 which is the exact pixel width. Unfortunately it does not seem to function as intended:

![image](https://user-images.githubusercontent.com/60113330/114286124-a6533000-9a21-11eb-8f1e-3fa558ea24bd.png)

**Comment by mitchej123** [comment]
Made some tweaks that should hopefully address this in beta 18

**Comment by facetorched** [comment]
Looks better but not perfect in 2.1.2 release
![image](https://user-images.githubusercontent.com/60113330/118068421-f8141080-b367-11eb-8759-b5487be4aad7.png)
