### ISSUE TITLE
[2.1.0-GTNH-beta18] Lexica Botanica as Icon produces black Rectangle on all Botania Tabs

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/NotEnoughItems#92]
Version: 2.1.0-GTNH-beta11 (non-GTNH modpack)

When using the Lexica Botanica as an tab icon, every Botania tab gets this black rectangle:
![grafik](https://user-images.githubusercontent.com/35727266/114286261-66aa3980-9a5d-11eb-8a73-9c286a78c963.png)
This only happens, when the Lexica Botania is rendered.

Used CSV:
[handlers.csv](https://github.com/GTNewHorizons/NotEnoughItems/files/6290875/handlers.csv)

**Comment by mitchej123** [comment]
Are you using any resource packs?
Any other handlers have this behavior?
Did you try adjusting the width of the handler?

**Comment by glowredman** [comment]
No resource packs.

I observed this only with Botania and only with the Petal Apothecary handler, the Runic Altar handler, the Mana Infusion handler, the Elven Trade handler, the Pure Daisy handler and the Lexica Botania handler. These handlers are ***only*** affected when a recipe query results in one or more "recipes" in the Lexica Botania tab, it being currently selected does not matter though.

Examples:
- "Floating Pure Daisy": entry in 'Floating Flowers' (no black bar), entry in 'Lexica Botania' (black bar visible)
- "Blaze Lamp": entry in 'Shaped Crafting' (no black bar), entry in 'Lexica Botania' (black bar visible)
- "Rosa Arcana": entry in 'Xtreme Crafting' (no black bar), entry in 'Petal Apothecary' (black bar visible), entries in 'Mana Infusion' (black bar visible), entry in 'Lexica Botania' (black bar visible)
- "White Tulip": entry in 'Mana Infusion' (no black bar)

If the black bar is shown depends on the ItemStack used as icon aswell.
Examples of ItemStacks which caused a black bar:
- Botania:lexicon
- Avaritia:Infinity_Pickaxe  {ench: [{lvl: 10 as short, id: 35 as short}]}
- minecraft:potion:16449
- minecraft:enchanted_book {StoredEnchantments: [{lvl: 4 as short, id: 0 as short}]}
- AWWayofTime:bloodMagicBaseAlchemyItems:6
- BiblioCraft:item.BiblioRedBook {redstonebook: "by glowredman"}
- Botania:gaiaHead
- IC2:itemFluidCell {Fluid: {FluidName: "water", Amount: 1000}}

Examples of ItemStacks which didn't cause a black bar:
- minecraft:stone
- minecraft:portal
- Avaritia:Neutron_Collector
- Avaritia:infinitato
- Avaritia:Resource:4
- BiomesOPlenty:biomeFinder
- BloodArsenal:life_imbued_chestplate {LPStored: 0}
- Botania:bifrostPerm
- DraconicEvolution:chaosFragment:2
- ExtraUtilities:greenscreen:11
- OpenBlocks:tank {tank: {FluidName: "lava", Amount: 16000}}
- avaritiaddons:CompressedChest
- eternalsingularity:eternal_singularity
- extracells:walrus
- headcrumbs:head {SkullOwner: {Name: "deadmau5"}}

Adjusting the hadler width changed nothing.

**Comment by mitchej123** [comment]
@glowredman Is this still an issue?  I haven't gotten around to looking into it.

**Comment by glowredman** [comment]
I think so, but I didn't check

**Comment by miozune** [comment]
Confirmed fix
