### ISSUE TITLE
[2.1.0-GTNH-beta15] hello, the 'handlers.csv' has some instruction to reload in the game?

### ISSUE THREAD

**Issue by Leaveleaf** [GTNewHorizons/NotEnoughItems#93]
hello, the 'handlers.csv' has some instruction to reload in the game?

**Comment by mitchej123** [comment]
Shift clicking the NEI Options wrench will reload the handlers.csv.

**Comment by Leaveleaf** [comment]
ok，thanks

**Comment by Leaveleaf** [comment]
some reika‘s mod handler

https://paste.ubuntu.com/p/5DGG4BDHt8/

Reika.RotaryCraft.ModInterface.NEI.ExtractorHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:20,,RotaryCraft,FALSE,,,90,166,4,,,,,,
Reika.RotaryCraft.ModInterface.NEI.WorktableRecipeHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:75,,RotaryCraft,FALSE,,,65,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.ToolChargingHandler,RotaryCraft,RotaryCraft:rotarycraft_item_spring,,RotaryCraft,FALSE,,,65,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.ToolCraftingHandler,RotaryCraft,minecraft:crafting_table,,RotaryCraft,FALSE,,,65,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.BlastFurnaceHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:45,,RotaryCraft,FALSE,,,115,166,2,,,,,,
Reika.RotaryCraft.ModInterface.NEI.GrinderHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:11,,RotaryCraft,FALSE,,,70,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.FermenterHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:7,,RotaryCraft,FALSE,,,70,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.CompactorHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:22,,RotaryCraft,FALSE,,,110,166,2,,,,,,
Reika.RotaryCraft.ModInterface.NEI.PulseJetHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:21,,RotaryCraft,FALSE,,,75,166,4,,,,,,
Reika.RotaryCraft.ModInterface.NEI.FractionHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:25,,RotaryCraft,FALSE,,,70,166,4,,,,,,
Reika.RotaryCraft.ModInterface.NEI.CrystallizerHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:110,,RotaryCraft,FALSE,,,75,166,4,,,,,,
Reika.RotaryCraft.ModInterface.NEI.FridgeHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:118,,RotaryCraft,FALSE,,,75,166,3,,,,,,
Reika.RotaryCraft.ModInterface.NEI.FillingStationHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:101,,RotaryCraft,FALSE,,,85,166,3,,,,,,
Reika.RotaryCraft.ModInterface.NEI.FrictionHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:67,,RotaryCraft,FALSE,,,115,166,2,,,,,,
Reika.RotaryCraft.ModInterface.NEI.ComposterHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:121,,RotaryCraft,FALSE,,,73,166,4,,,,,,
Reika.RotaryCraft.ModInterface.NEI.LavaMakerHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:91,,RotaryCraft,FALSE,,,95,166,2,,,,,,
Reika.RotaryCraft.ModInterface.NEI.CentrifugeHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:125,,RotaryCraft,FALSE,,,75,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.DryingBedHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:127,,RotaryCraft,FALSE,,,75,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.WetterHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:128,,RotaryCraft,FALSE,,,75,166,5,,,,,,
Reika.RotaryCraft.ModInterface.NEI.FuelEnhancerHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:100,,RotaryCraft,FALSE,,,90,166,2,,,,,,
Reika.RotaryCraft.ModInterface.NEI.DropProcessorHandler,RotaryCraft,RotaryCraft:rotarycraft_item_machine:129,,RotaryCraft,FALSE,,,75,166,5,,,,,,
Reika.ReactorCraft.NEI.SynthesizerHandler,ReactorCraft,ReactorCraft:reactorcraft_item_placer:14,,ReactorCraft,FALSE,,,80,166,4,,,,,,
Reika.ReactorCraft.NEI.UProcessorHandler,ReactorCraft,ReactorCraft:reactorcraft_item_placer:9,,ReactorCraft,FALSE,,,75,166,4,,,,,,
Reika.ReactorCraft.NEI.CentrifugeHandler,ReactorCraft,ReactorCraft:reactorcraft_item_placer:8,,ReactorCraft,FALSE,,,90,166,3,,,,,,
Reika.ReactorCraft.NEI.ElectrolyzerHandler,ReactorCraft,ReactorCraft:reactorcraft_item_placer:16,,ReactorCraft,FALSE,,,90,166,3,,,,,,
Reika.ChromatiCraft.ModInterface.NEI.CrystalBrewerHandler,ChromatiCraft,ChromatiCraft:chromaticraft_item_placer:7,,ChromatiCraft,FALSE,,,65,166,5,,,,,,
Reika.ChromatiCraft.ModInterface.NEI.CrystalFurnaceHandler,ChromatiCraft,ChromatiCraft:chromaticraft_item_placer:15,,ChromatiCraft,FALSE,,,65,166,5,,,,,,
Reika.ChromatiCraft.ModInterface.NEI.GlowFireHandler,ChromatiCraft,ChromatiCraft:chromaticraft_item_placer:60,,ChromatiCraft,FALSE,,,145,166,2,,,,,,
Reika.ChromatiCraft.ModInterface.NEI.EnchantDecompHandler,ChromatiCraft,ChromatiCraft:chromaticraft_item_placer:69,,ChromatiCraft,FALSE,,,65,166,5,,,,,,
Reika.ChromatiCraft.ModInterface.NEI.FabricatorHandler,ChromatiCraft,ChromatiCraft:chromaticraft_item_placer:23,,ChromatiCraft,FALSE,,,175,166,1,,,,,,
Reika.ChromatiCraft.ModInterface.NEI.PlantDustHandler,ChromatiCraft,ChromatiCraft:chromaticraft_block_tieredplant,,ChromatiCraft,FALSE,,,65,166,5,,,,,,
