### ISSUE TITLE
[2.1.0.6b-GTNH-beta18] Planets' list now show on Vein Stats

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/NotEnoughItems#97]
I can't see the generated worlds list while i'm in fullscreen, but i can when windowed. (the red dot is the where the mouse is)
![2021-04-14_13 21 24](https://user-images.githubusercontent.com/57275066/114746420-1ca7a900-9d26-11eb-888e-5c3fe6ee6067.png)
![2021-04-14_13 15 47](https://user-images.githubusercontent.com/57275066/114746423-1d403f80-9d26-11eb-90bd-c53398fd74d0.png)

**Comment by Prometheus0000** [comment]
Starts at the Eu, Te
![image](https://user-images.githubusercontent.com/8517039/118363842-3d9d2d00-b564-11eb-8a7a-b7c72ffd4f1b.png)
Goes all the way down to the bottom of the image.
![image](https://user-images.githubusercontent.com/8517039/118363817-278f6c80-b564-11eb-9813-ae7855a8b211.png)

I'd say it both needs to be shifted up, and needs to be made a much smaller area in the GT5U code.

**Comment by mitchej123** [comment]
I think this was recently addressed
